################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/string/bcmp.c \
../src/string/bcopy.c \
../src/string/bzero.c \
../src/string/index.c \
../src/string/memccpy.c \
../src/string/memchr.c \
../src/string/memcmp.c \
../src/string/memmem.c \
../src/string/memmove.c \
../src/string/mempcpy.c \
../src/string/memrchr.c \
../src/string/memset.c \
../src/string/rindex.c \
../src/string/stpcpy.c \
../src/string/stpncpy.c \
../src/string/strcasecmp.c \
../src/string/strcasestr.c \
../src/string/strcat.c \
../src/string/strchr.c \
../src/string/strchrnul.c \
../src/string/strcmp.c \
../src/string/strcpy.c \
../src/string/strcspn.c \
../src/string/strdup.c \
../src/string/strerror_r.c \
../src/string/strlcat.c \
../src/string/strlcpy.c \
../src/string/strlen.c \
../src/string/strncasecmp.c \
../src/string/strncat.c \
../src/string/strncmp.c \
../src/string/strncpy.c \
../src/string/strndup.c \
../src/string/strnlen.c \
../src/string/strpbrk.c \
../src/string/strrchr.c \
../src/string/strsep.c \
../src/string/strsignal.c \
../src/string/strspn.c \
../src/string/strstr.c \
../src/string/strtok.c \
../src/string/strtok_r.c \
../src/string/strverscmp.c \
../src/string/swab.c \
../src/string/wcpcpy.c \
../src/string/wcpncpy.c \
../src/string/wcscasecmp.c \
../src/string/wcscasecmp_l.c \
../src/string/wcscat.c \
../src/string/wcschr.c \
../src/string/wcscmp.c \
../src/string/wcscpy.c \
../src/string/wcscspn.c \
../src/string/wcsdup.c \
../src/string/wcslen.c \
../src/string/wcsncasecmp.c \
../src/string/wcsncasecmp_l.c \
../src/string/wcsncat.c \
../src/string/wcsncmp.c \
../src/string/wcsncpy.c \
../src/string/wcsnlen.c \
../src/string/wcspbrk.c \
../src/string/wcsrchr.c \
../src/string/wcsspn.c \
../src/string/wcsstr.c \
../src/string/wcstok.c \
../src/string/wcswcs.c \
../src/string/wmemchr.c \
../src/string/wmemcmp.c \
../src/string/wmemcpy.c \
../src/string/wmemmove.c \
../src/string/wmemset.c 

C_DEPS += \
./src/string/bcmp.d \
./src/string/bcopy.d \
./src/string/bzero.d \
./src/string/index.d \
./src/string/memccpy.d \
./src/string/memchr.d \
./src/string/memcmp.d \
./src/string/memmem.d \
./src/string/memmove.d \
./src/string/mempcpy.d \
./src/string/memrchr.d \
./src/string/memset.d \
./src/string/rindex.d \
./src/string/stpcpy.d \
./src/string/stpncpy.d \
./src/string/strcasecmp.d \
./src/string/strcasestr.d \
./src/string/strcat.d \
./src/string/strchr.d \
./src/string/strchrnul.d \
./src/string/strcmp.d \
./src/string/strcpy.d \
./src/string/strcspn.d \
./src/string/strdup.d \
./src/string/strerror_r.d \
./src/string/strlcat.d \
./src/string/strlcpy.d \
./src/string/strlen.d \
./src/string/strncasecmp.d \
./src/string/strncat.d \
./src/string/strncmp.d \
./src/string/strncpy.d \
./src/string/strndup.d \
./src/string/strnlen.d \
./src/string/strpbrk.d \
./src/string/strrchr.d \
./src/string/strsep.d \
./src/string/strsignal.d \
./src/string/strspn.d \
./src/string/strstr.d \
./src/string/strtok.d \
./src/string/strtok_r.d \
./src/string/strverscmp.d \
./src/string/swab.d \
./src/string/wcpcpy.d \
./src/string/wcpncpy.d \
./src/string/wcscasecmp.d \
./src/string/wcscasecmp_l.d \
./src/string/wcscat.d \
./src/string/wcschr.d \
./src/string/wcscmp.d \
./src/string/wcscpy.d \
./src/string/wcscspn.d \
./src/string/wcsdup.d \
./src/string/wcslen.d \
./src/string/wcsncasecmp.d \
./src/string/wcsncasecmp_l.d \
./src/string/wcsncat.d \
./src/string/wcsncmp.d \
./src/string/wcsncpy.d \
./src/string/wcsnlen.d \
./src/string/wcspbrk.d \
./src/string/wcsrchr.d \
./src/string/wcsspn.d \
./src/string/wcsstr.d \
./src/string/wcstok.d \
./src/string/wcswcs.d \
./src/string/wmemchr.d \
./src/string/wmemcmp.d \
./src/string/wmemcpy.d \
./src/string/wmemmove.d \
./src/string/wmemset.d 

OBJS += \
./src/string/bcmp.o \
./src/string/bcopy.o \
./src/string/bzero.o \
./src/string/index.o \
./src/string/memccpy.o \
./src/string/memchr.o \
./src/string/memcmp.o \
./src/string/memmem.o \
./src/string/memmove.o \
./src/string/mempcpy.o \
./src/string/memrchr.o \
./src/string/memset.o \
./src/string/rindex.o \
./src/string/stpcpy.o \
./src/string/stpncpy.o \
./src/string/strcasecmp.o \
./src/string/strcasestr.o \
./src/string/strcat.o \
./src/string/strchr.o \
./src/string/strchrnul.o \
./src/string/strcmp.o \
./src/string/strcpy.o \
./src/string/strcspn.o \
./src/string/strdup.o \
./src/string/strerror_r.o \
./src/string/strlcat.o \
./src/string/strlcpy.o \
./src/string/strlen.o \
./src/string/strncasecmp.o \
./src/string/strncat.o \
./src/string/strncmp.o \
./src/string/strncpy.o \
./src/string/strndup.o \
./src/string/strnlen.o \
./src/string/strpbrk.o \
./src/string/strrchr.o \
./src/string/strsep.o \
./src/string/strsignal.o \
./src/string/strspn.o \
./src/string/strstr.o \
./src/string/strtok.o \
./src/string/strtok_r.o \
./src/string/strverscmp.o \
./src/string/swab.o \
./src/string/wcpcpy.o \
./src/string/wcpncpy.o \
./src/string/wcscasecmp.o \
./src/string/wcscasecmp_l.o \
./src/string/wcscat.o \
./src/string/wcschr.o \
./src/string/wcscmp.o \
./src/string/wcscpy.o \
./src/string/wcscspn.o \
./src/string/wcsdup.o \
./src/string/wcslen.o \
./src/string/wcsncasecmp.o \
./src/string/wcsncasecmp_l.o \
./src/string/wcsncat.o \
./src/string/wcsncmp.o \
./src/string/wcsncpy.o \
./src/string/wcsnlen.o \
./src/string/wcspbrk.o \
./src/string/wcsrchr.o \
./src/string/wcsspn.o \
./src/string/wcsstr.o \
./src/string/wcstok.o \
./src/string/wcswcs.o \
./src/string/wmemchr.o \
./src/string/wmemcmp.o \
./src/string/wmemcpy.o \
./src/string/wmemmove.o \
./src/string/wmemset.o 


# Each subdirectory must supply rules for building sources it contributes
src/string/%.o: ../src/string/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

