################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/stdio/__fclose_ca.c \
../src/stdio/__fdopen.c \
../src/stdio/__fmodeflags.c \
../src/stdio/__fopen_rb_ca.c \
../src/stdio/__lockfile.c \
../src/stdio/__overflow.c \
../src/stdio/__stdio_close.c \
../src/stdio/__stdio_exit.c \
../src/stdio/__stdio_read.c \
../src/stdio/__stdio_seek.c \
../src/stdio/__stdio_write.c \
../src/stdio/__stdout_write.c \
../src/stdio/__string_read.c \
../src/stdio/__toread.c \
../src/stdio/__towrite.c \
../src/stdio/__uflow.c \
../src/stdio/asprintf.c \
../src/stdio/clearerr.c \
../src/stdio/dprintf.c \
../src/stdio/ext.c \
../src/stdio/ext2.c \
../src/stdio/fclose.c \
../src/stdio/feof.c \
../src/stdio/ferror.c \
../src/stdio/fflush.c \
../src/stdio/fgetc.c \
../src/stdio/fgetln.c \
../src/stdio/fgetpos.c \
../src/stdio/fgets.c \
../src/stdio/fgetwc.c \
../src/stdio/fgetws.c \
../src/stdio/fileno.c \
../src/stdio/flockfile.c \
../src/stdio/fmemopen.c \
../src/stdio/fopen.c \
../src/stdio/fprintf.c \
../src/stdio/fputc.c \
../src/stdio/fputs.c \
../src/stdio/fputwc.c \
../src/stdio/fputws.c \
../src/stdio/fread.c \
../src/stdio/freopen.c \
../src/stdio/fscanf.c \
../src/stdio/fseek.c \
../src/stdio/fsetpos.c \
../src/stdio/ftell.c \
../src/stdio/ftrylockfile.c \
../src/stdio/funlockfile.c \
../src/stdio/fwide.c \
../src/stdio/fwprintf.c \
../src/stdio/fwrite.c \
../src/stdio/fwscanf.c \
../src/stdio/getc.c \
../src/stdio/getc_unlocked.c \
../src/stdio/getchar.c \
../src/stdio/getchar_unlocked.c \
../src/stdio/getdelim.c \
../src/stdio/getline.c \
../src/stdio/gets.c \
../src/stdio/getw.c \
../src/stdio/getwc.c \
../src/stdio/getwchar.c \
../src/stdio/ofl.c \
../src/stdio/ofl_add.c \
../src/stdio/open_memstream.c \
../src/stdio/open_wmemstream.c \
../src/stdio/pclose.c \
../src/stdio/perror.c \
../src/stdio/popen.c \
../src/stdio/printf.c \
../src/stdio/putc.c \
../src/stdio/putc_unlocked.c \
../src/stdio/putchar.c \
../src/stdio/putchar_unlocked.c \
../src/stdio/puts.c \
../src/stdio/putw.c \
../src/stdio/putwc.c \
../src/stdio/putwchar.c \
../src/stdio/remove.c \
../src/stdio/rename.c \
../src/stdio/rewind.c \
../src/stdio/scanf.c \
../src/stdio/setbuf.c \
../src/stdio/setbuffer.c \
../src/stdio/setlinebuf.c \
../src/stdio/setvbuf.c \
../src/stdio/snprintf.c \
../src/stdio/sprintf.c \
../src/stdio/sscanf.c \
../src/stdio/stderr.c \
../src/stdio/stdin.c \
../src/stdio/stdout.c \
../src/stdio/swprintf.c \
../src/stdio/swscanf.c \
../src/stdio/tempnam.c \
../src/stdio/tmpfile.c \
../src/stdio/tmpnam.c \
../src/stdio/ungetc.c \
../src/stdio/ungetwc.c \
../src/stdio/vasprintf.c \
../src/stdio/vdprintf.c \
../src/stdio/vfprintf.c \
../src/stdio/vfscanf.c \
../src/stdio/vfwprintf.c \
../src/stdio/vfwscanf.c \
../src/stdio/vprintf.c \
../src/stdio/vscanf.c \
../src/stdio/vsnprintf.c \
../src/stdio/vsprintf.c \
../src/stdio/vsscanf.c \
../src/stdio/vswprintf.c \
../src/stdio/vswscanf.c \
../src/stdio/vwprintf.c \
../src/stdio/vwscanf.c \
../src/stdio/wprintf.c \
../src/stdio/wscanf.c 

C_DEPS += \
./src/stdio/__fclose_ca.d \
./src/stdio/__fdopen.d \
./src/stdio/__fmodeflags.d \
./src/stdio/__fopen_rb_ca.d \
./src/stdio/__lockfile.d \
./src/stdio/__overflow.d \
./src/stdio/__stdio_close.d \
./src/stdio/__stdio_exit.d \
./src/stdio/__stdio_read.d \
./src/stdio/__stdio_seek.d \
./src/stdio/__stdio_write.d \
./src/stdio/__stdout_write.d \
./src/stdio/__string_read.d \
./src/stdio/__toread.d \
./src/stdio/__towrite.d \
./src/stdio/__uflow.d \
./src/stdio/asprintf.d \
./src/stdio/clearerr.d \
./src/stdio/dprintf.d \
./src/stdio/ext.d \
./src/stdio/ext2.d \
./src/stdio/fclose.d \
./src/stdio/feof.d \
./src/stdio/ferror.d \
./src/stdio/fflush.d \
./src/stdio/fgetc.d \
./src/stdio/fgetln.d \
./src/stdio/fgetpos.d \
./src/stdio/fgets.d \
./src/stdio/fgetwc.d \
./src/stdio/fgetws.d \
./src/stdio/fileno.d \
./src/stdio/flockfile.d \
./src/stdio/fmemopen.d \
./src/stdio/fopen.d \
./src/stdio/fprintf.d \
./src/stdio/fputc.d \
./src/stdio/fputs.d \
./src/stdio/fputwc.d \
./src/stdio/fputws.d \
./src/stdio/fread.d \
./src/stdio/freopen.d \
./src/stdio/fscanf.d \
./src/stdio/fseek.d \
./src/stdio/fsetpos.d \
./src/stdio/ftell.d \
./src/stdio/ftrylockfile.d \
./src/stdio/funlockfile.d \
./src/stdio/fwide.d \
./src/stdio/fwprintf.d \
./src/stdio/fwrite.d \
./src/stdio/fwscanf.d \
./src/stdio/getc.d \
./src/stdio/getc_unlocked.d \
./src/stdio/getchar.d \
./src/stdio/getchar_unlocked.d \
./src/stdio/getdelim.d \
./src/stdio/getline.d \
./src/stdio/gets.d \
./src/stdio/getw.d \
./src/stdio/getwc.d \
./src/stdio/getwchar.d \
./src/stdio/ofl.d \
./src/stdio/ofl_add.d \
./src/stdio/open_memstream.d \
./src/stdio/open_wmemstream.d \
./src/stdio/pclose.d \
./src/stdio/perror.d \
./src/stdio/popen.d \
./src/stdio/printf.d \
./src/stdio/putc.d \
./src/stdio/putc_unlocked.d \
./src/stdio/putchar.d \
./src/stdio/putchar_unlocked.d \
./src/stdio/puts.d \
./src/stdio/putw.d \
./src/stdio/putwc.d \
./src/stdio/putwchar.d \
./src/stdio/remove.d \
./src/stdio/rename.d \
./src/stdio/rewind.d \
./src/stdio/scanf.d \
./src/stdio/setbuf.d \
./src/stdio/setbuffer.d \
./src/stdio/setlinebuf.d \
./src/stdio/setvbuf.d \
./src/stdio/snprintf.d \
./src/stdio/sprintf.d \
./src/stdio/sscanf.d \
./src/stdio/stderr.d \
./src/stdio/stdin.d \
./src/stdio/stdout.d \
./src/stdio/swprintf.d \
./src/stdio/swscanf.d \
./src/stdio/tempnam.d \
./src/stdio/tmpfile.d \
./src/stdio/tmpnam.d \
./src/stdio/ungetc.d \
./src/stdio/ungetwc.d \
./src/stdio/vasprintf.d \
./src/stdio/vdprintf.d \
./src/stdio/vfprintf.d \
./src/stdio/vfscanf.d \
./src/stdio/vfwprintf.d \
./src/stdio/vfwscanf.d \
./src/stdio/vprintf.d \
./src/stdio/vscanf.d \
./src/stdio/vsnprintf.d \
./src/stdio/vsprintf.d \
./src/stdio/vsscanf.d \
./src/stdio/vswprintf.d \
./src/stdio/vswscanf.d \
./src/stdio/vwprintf.d \
./src/stdio/vwscanf.d \
./src/stdio/wprintf.d \
./src/stdio/wscanf.d 

OBJS += \
./src/stdio/__fclose_ca.o \
./src/stdio/__fdopen.o \
./src/stdio/__fmodeflags.o \
./src/stdio/__fopen_rb_ca.o \
./src/stdio/__lockfile.o \
./src/stdio/__overflow.o \
./src/stdio/__stdio_close.o \
./src/stdio/__stdio_exit.o \
./src/stdio/__stdio_read.o \
./src/stdio/__stdio_seek.o \
./src/stdio/__stdio_write.o \
./src/stdio/__stdout_write.o \
./src/stdio/__string_read.o \
./src/stdio/__toread.o \
./src/stdio/__towrite.o \
./src/stdio/__uflow.o \
./src/stdio/asprintf.o \
./src/stdio/clearerr.o \
./src/stdio/dprintf.o \
./src/stdio/ext.o \
./src/stdio/ext2.o \
./src/stdio/fclose.o \
./src/stdio/feof.o \
./src/stdio/ferror.o \
./src/stdio/fflush.o \
./src/stdio/fgetc.o \
./src/stdio/fgetln.o \
./src/stdio/fgetpos.o \
./src/stdio/fgets.o \
./src/stdio/fgetwc.o \
./src/stdio/fgetws.o \
./src/stdio/fileno.o \
./src/stdio/flockfile.o \
./src/stdio/fmemopen.o \
./src/stdio/fopen.o \
./src/stdio/fprintf.o \
./src/stdio/fputc.o \
./src/stdio/fputs.o \
./src/stdio/fputwc.o \
./src/stdio/fputws.o \
./src/stdio/fread.o \
./src/stdio/freopen.o \
./src/stdio/fscanf.o \
./src/stdio/fseek.o \
./src/stdio/fsetpos.o \
./src/stdio/ftell.o \
./src/stdio/ftrylockfile.o \
./src/stdio/funlockfile.o \
./src/stdio/fwide.o \
./src/stdio/fwprintf.o \
./src/stdio/fwrite.o \
./src/stdio/fwscanf.o \
./src/stdio/getc.o \
./src/stdio/getc_unlocked.o \
./src/stdio/getchar.o \
./src/stdio/getchar_unlocked.o \
./src/stdio/getdelim.o \
./src/stdio/getline.o \
./src/stdio/gets.o \
./src/stdio/getw.o \
./src/stdio/getwc.o \
./src/stdio/getwchar.o \
./src/stdio/ofl.o \
./src/stdio/ofl_add.o \
./src/stdio/open_memstream.o \
./src/stdio/open_wmemstream.o \
./src/stdio/pclose.o \
./src/stdio/perror.o \
./src/stdio/popen.o \
./src/stdio/printf.o \
./src/stdio/putc.o \
./src/stdio/putc_unlocked.o \
./src/stdio/putchar.o \
./src/stdio/putchar_unlocked.o \
./src/stdio/puts.o \
./src/stdio/putw.o \
./src/stdio/putwc.o \
./src/stdio/putwchar.o \
./src/stdio/remove.o \
./src/stdio/rename.o \
./src/stdio/rewind.o \
./src/stdio/scanf.o \
./src/stdio/setbuf.o \
./src/stdio/setbuffer.o \
./src/stdio/setlinebuf.o \
./src/stdio/setvbuf.o \
./src/stdio/snprintf.o \
./src/stdio/sprintf.o \
./src/stdio/sscanf.o \
./src/stdio/stderr.o \
./src/stdio/stdin.o \
./src/stdio/stdout.o \
./src/stdio/swprintf.o \
./src/stdio/swscanf.o \
./src/stdio/tempnam.o \
./src/stdio/tmpfile.o \
./src/stdio/tmpnam.o \
./src/stdio/ungetc.o \
./src/stdio/ungetwc.o \
./src/stdio/vasprintf.o \
./src/stdio/vdprintf.o \
./src/stdio/vfprintf.o \
./src/stdio/vfscanf.o \
./src/stdio/vfwprintf.o \
./src/stdio/vfwscanf.o \
./src/stdio/vprintf.o \
./src/stdio/vscanf.o \
./src/stdio/vsnprintf.o \
./src/stdio/vsprintf.o \
./src/stdio/vsscanf.o \
./src/stdio/vswprintf.o \
./src/stdio/vswscanf.o \
./src/stdio/vwprintf.o \
./src/stdio/vwscanf.o \
./src/stdio/wprintf.o \
./src/stdio/wscanf.o 


# Each subdirectory must supply rules for building sources it contributes
src/stdio/%.o: ../src/stdio/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

