################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/unistd/_exit.c \
../src/unistd/access.c \
../src/unistd/acct.c \
../src/unistd/alarm.c \
../src/unistd/chdir.c \
../src/unistd/chown.c \
../src/unistd/close.c \
../src/unistd/ctermid.c \
../src/unistd/dup.c \
../src/unistd/dup2.c \
../src/unistd/dup3.c \
../src/unistd/faccessat.c \
../src/unistd/fchdir.c \
../src/unistd/fchown.c \
../src/unistd/fchownat.c \
../src/unistd/fdatasync.c \
../src/unistd/fsync.c \
../src/unistd/ftruncate.c \
../src/unistd/getcwd.c \
../src/unistd/getegid.c \
../src/unistd/geteuid.c \
../src/unistd/getgid.c \
../src/unistd/getgroups.c \
../src/unistd/gethostname.c \
../src/unistd/getlogin.c \
../src/unistd/getlogin_r.c \
../src/unistd/getpgid.c \
../src/unistd/getpgrp.c \
../src/unistd/getpid.c \
../src/unistd/getppid.c \
../src/unistd/getsid.c \
../src/unistd/getuid.c \
../src/unistd/isatty.c \
../src/unistd/lchown.c \
../src/unistd/link.c \
../src/unistd/linkat.c \
../src/unistd/lseek.c \
../src/unistd/nice.c \
../src/unistd/pause.c \
../src/unistd/pipe.c \
../src/unistd/pipe2.c \
../src/unistd/posix_close.c \
../src/unistd/pread.c \
../src/unistd/preadv.c \
../src/unistd/pwrite.c \
../src/unistd/pwritev.c \
../src/unistd/read.c \
../src/unistd/readlink.c \
../src/unistd/readlinkat.c \
../src/unistd/readv.c \
../src/unistd/renameat.c \
../src/unistd/rmdir.c \
../src/unistd/setegid.c \
../src/unistd/seteuid.c \
../src/unistd/setgid.c \
../src/unistd/setpgid.c \
../src/unistd/setpgrp.c \
../src/unistd/setregid.c \
../src/unistd/setresgid.c \
../src/unistd/setresuid.c \
../src/unistd/setreuid.c \
../src/unistd/setsid.c \
../src/unistd/setuid.c \
../src/unistd/setxid.c \
../src/unistd/sleep.c \
../src/unistd/symlink.c \
../src/unistd/symlinkat.c \
../src/unistd/sync.c \
../src/unistd/tcgetpgrp.c \
../src/unistd/tcsetpgrp.c \
../src/unistd/truncate.c \
../src/unistd/ttyname.c \
../src/unistd/ttyname_r.c \
../src/unistd/ualarm.c \
../src/unistd/unlink.c \
../src/unistd/unlinkat.c \
../src/unistd/usleep.c \
../src/unistd/write.c \
../src/unistd/writev.c 

C_DEPS += \
./src/unistd/_exit.d \
./src/unistd/access.d \
./src/unistd/acct.d \
./src/unistd/alarm.d \
./src/unistd/chdir.d \
./src/unistd/chown.d \
./src/unistd/close.d \
./src/unistd/ctermid.d \
./src/unistd/dup.d \
./src/unistd/dup2.d \
./src/unistd/dup3.d \
./src/unistd/faccessat.d \
./src/unistd/fchdir.d \
./src/unistd/fchown.d \
./src/unistd/fchownat.d \
./src/unistd/fdatasync.d \
./src/unistd/fsync.d \
./src/unistd/ftruncate.d \
./src/unistd/getcwd.d \
./src/unistd/getegid.d \
./src/unistd/geteuid.d \
./src/unistd/getgid.d \
./src/unistd/getgroups.d \
./src/unistd/gethostname.d \
./src/unistd/getlogin.d \
./src/unistd/getlogin_r.d \
./src/unistd/getpgid.d \
./src/unistd/getpgrp.d \
./src/unistd/getpid.d \
./src/unistd/getppid.d \
./src/unistd/getsid.d \
./src/unistd/getuid.d \
./src/unistd/isatty.d \
./src/unistd/lchown.d \
./src/unistd/link.d \
./src/unistd/linkat.d \
./src/unistd/lseek.d \
./src/unistd/nice.d \
./src/unistd/pause.d \
./src/unistd/pipe.d \
./src/unistd/pipe2.d \
./src/unistd/posix_close.d \
./src/unistd/pread.d \
./src/unistd/preadv.d \
./src/unistd/pwrite.d \
./src/unistd/pwritev.d \
./src/unistd/read.d \
./src/unistd/readlink.d \
./src/unistd/readlinkat.d \
./src/unistd/readv.d \
./src/unistd/renameat.d \
./src/unistd/rmdir.d \
./src/unistd/setegid.d \
./src/unistd/seteuid.d \
./src/unistd/setgid.d \
./src/unistd/setpgid.d \
./src/unistd/setpgrp.d \
./src/unistd/setregid.d \
./src/unistd/setresgid.d \
./src/unistd/setresuid.d \
./src/unistd/setreuid.d \
./src/unistd/setsid.d \
./src/unistd/setuid.d \
./src/unistd/setxid.d \
./src/unistd/sleep.d \
./src/unistd/symlink.d \
./src/unistd/symlinkat.d \
./src/unistd/sync.d \
./src/unistd/tcgetpgrp.d \
./src/unistd/tcsetpgrp.d \
./src/unistd/truncate.d \
./src/unistd/ttyname.d \
./src/unistd/ttyname_r.d \
./src/unistd/ualarm.d \
./src/unistd/unlink.d \
./src/unistd/unlinkat.d \
./src/unistd/usleep.d \
./src/unistd/write.d \
./src/unistd/writev.d 

OBJS += \
./src/unistd/_exit.o \
./src/unistd/access.o \
./src/unistd/acct.o \
./src/unistd/alarm.o \
./src/unistd/chdir.o \
./src/unistd/chown.o \
./src/unistd/close.o \
./src/unistd/ctermid.o \
./src/unistd/dup.o \
./src/unistd/dup2.o \
./src/unistd/dup3.o \
./src/unistd/faccessat.o \
./src/unistd/fchdir.o \
./src/unistd/fchown.o \
./src/unistd/fchownat.o \
./src/unistd/fdatasync.o \
./src/unistd/fsync.o \
./src/unistd/ftruncate.o \
./src/unistd/getcwd.o \
./src/unistd/getegid.o \
./src/unistd/geteuid.o \
./src/unistd/getgid.o \
./src/unistd/getgroups.o \
./src/unistd/gethostname.o \
./src/unistd/getlogin.o \
./src/unistd/getlogin_r.o \
./src/unistd/getpgid.o \
./src/unistd/getpgrp.o \
./src/unistd/getpid.o \
./src/unistd/getppid.o \
./src/unistd/getsid.o \
./src/unistd/getuid.o \
./src/unistd/isatty.o \
./src/unistd/lchown.o \
./src/unistd/link.o \
./src/unistd/linkat.o \
./src/unistd/lseek.o \
./src/unistd/nice.o \
./src/unistd/pause.o \
./src/unistd/pipe.o \
./src/unistd/pipe2.o \
./src/unistd/posix_close.o \
./src/unistd/pread.o \
./src/unistd/preadv.o \
./src/unistd/pwrite.o \
./src/unistd/pwritev.o \
./src/unistd/read.o \
./src/unistd/readlink.o \
./src/unistd/readlinkat.o \
./src/unistd/readv.o \
./src/unistd/renameat.o \
./src/unistd/rmdir.o \
./src/unistd/setegid.o \
./src/unistd/seteuid.o \
./src/unistd/setgid.o \
./src/unistd/setpgid.o \
./src/unistd/setpgrp.o \
./src/unistd/setregid.o \
./src/unistd/setresgid.o \
./src/unistd/setresuid.o \
./src/unistd/setreuid.o \
./src/unistd/setsid.o \
./src/unistd/setuid.o \
./src/unistd/setxid.o \
./src/unistd/sleep.o \
./src/unistd/symlink.o \
./src/unistd/symlinkat.o \
./src/unistd/sync.o \
./src/unistd/tcgetpgrp.o \
./src/unistd/tcsetpgrp.o \
./src/unistd/truncate.o \
./src/unistd/ttyname.o \
./src/unistd/ttyname_r.o \
./src/unistd/ualarm.o \
./src/unistd/unlink.o \
./src/unistd/unlinkat.o \
./src/unistd/usleep.o \
./src/unistd/write.o \
./src/unistd/writev.o 


# Each subdirectory must supply rules for building sources it contributes
src/unistd/%.o: ../src/unistd/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

