/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tGeneralLighting_templ.c => src/tGeneralLighting.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tGeneralLighting_tecsgen.h"
#include "gpio_api.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* 電源LED */
gpio_t pow_led;
/* リレー出力 */
gpio_t relay_sw;
/* カラーLED */
gpio_t led_blue, led_green, led_red;
/* ユーザースイッチ CN16-4 */
gpio_t sw1, sw2;

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eGeneralLighting
 * entry port: eGeneralLighting
 * signature:  sGeneralLighting
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_Automatic
 * name:         eGeneralLighting_setLightingModeSetting_Automatic
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_Automatic
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_Automatic(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_NormalLighting
 * name:         eGeneralLighting_setLightingModeSetting_NormalLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_NormalLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_NormalLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_NightLighting
 * name:         eGeneralLighting_setLightingModeSetting_NightLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_NightLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_NightLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_ColorLighting
 * name:         eGeneralLighting_setLightingModeSetting_ColorLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_ColorLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_ColorLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_Automatic
 * name:         eGeneralLighting_getLightingModeSetting_Automatic
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_Automatic
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_Automatic(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_NormalLighting
 * name:         eGeneralLighting_getLightingModeSetting_NormalLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_NormalLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_NormalLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_NightLighting
 * name:         eGeneralLighting_getLightingModeSetting_NightLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_NightLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_NightLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_ColorLighting
 * name:         eGeneralLighting_getLightingModeSetting_ColorLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_ColorLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_ColorLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setOperatingStatus_ON
 * name:         eGeneralLighting_setOperatingStatus_ON
 * global_name:  tGeneralLighting_eGeneralLighting_setOperatingStatus_ON
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setOperatingStatus_ON(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	gpio_write(&pow_led, 1);
	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getOperatingStatus_ON
 * name:         eGeneralLighting_getOperatingStatus_ON
 * global_name:  tGeneralLighting_eGeneralLighting_getOperatingStatus_ON
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getOperatingStatus_ON(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setOperatingStatus_OFF
 * name:         eGeneralLighting_setOperatingStatus_OFF
 * global_name:  tGeneralLighting_eGeneralLighting_setOperatingStatus_OFF
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setOperatingStatus_OFF(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	gpio_write(&pow_led, 0);
	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getOperatingStatus_OFF
 * name:         eGeneralLighting_getOperatingStatus_OFF
 * global_name:  tGeneralLighting_eGeneralLighting_getOperatingStatus_OFF
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getOperatingStatus_OFF(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setFaultStatus_Fault
 * name:         eGeneralLighting_setFaultStatus_Fault
 * global_name:  tGeneralLighting_eGeneralLighting_setFaultStatus_Fault
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setFaultStatus_Fault(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getFaultStatus_Fault
 * name:         eGeneralLighting_getFaultStatus_Fault
 * global_name:  tGeneralLighting_eGeneralLighting_getFaultStatus_Fault
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getFaultStatus_Fault(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setFaultStatus_NoFault
 * name:         eGeneralLighting_setFaultStatus_NoFault
 * global_name:  tGeneralLighting_eGeneralLighting_setFaultStatus_NoFault
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setFaultStatus_NoFault(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getFaultStatus_NoFault
 * name:         eGeneralLighting_getFaultStatus_NoFault
 * global_name:  tGeneralLighting_eGeneralLighting_getFaultStatus_NoFault
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getFaultStatus_NoFault(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
