/* echonet_cfg.h */
#ifndef TOPPERS_ECHONET_CFG_H
#define TOPPERS_ECHONET_CFG_H

#include "echonet_app_config.h"

#define TNUM_ENODID	5

#define TNUM_EOBJID	10

#define NODE_PROFILE_EOBJ	1
#define HOME_AIR_CONDITIONER_EOBJ	2
#define TEMP_SENSOR_01_ENOD	3
#define TEMP_SENSOR_01_EOBJ	4
#define TEMP_SENSOR_02_ENOD	5
#define TEMP_SENSOR_02_EOBJ	6
#define TEMP_SENSOR_03_ENOD	7
#define TEMP_SENSOR_03_EOBJ	8
#define TEMP_SENSOR_04_ENOD	9
#define TEMP_SENSOR_04_EOBJ	10

#define TNUM_NODE_PROFILE_EOBJ_EPRPNO	13
#define TNUM_HOME_AIR_CONDITIONER_EOBJ_EPRPNO	10
#define TNUM_TEMP_SENSOR_01_ENOD_EPRPNO	13
#define TNUM_TEMP_SENSOR_01_EOBJ_EPRPNO	9
#define TNUM_TEMP_SENSOR_02_ENOD_EPRPNO	13
#define TNUM_TEMP_SENSOR_02_EOBJ_EPRPNO	9
#define TNUM_TEMP_SENSOR_03_ENOD_EPRPNO	13
#define TNUM_TEMP_SENSOR_03_EOBJ_EPRPNO	9
#define TNUM_TEMP_SENSOR_04_ENOD_EPRPNO	13
#define TNUM_TEMP_SENSOR_04_EOBJ_EPRPNO	9

#define TNUM_NODE_PROFILE_EOBJ_EOBJNO	1
#define TNUM_TEMP_SENSOR_01_ENOD_EOBJNO	1
#define TNUM_TEMP_SENSOR_02_ENOD_EOBJNO	1
#define TNUM_TEMP_SENSOR_03_ENOD_EOBJNO	1
#define TNUM_TEMP_SENSOR_04_ENOD_EOBJNO	1

#ifndef TNUM_ENODADR
#define TNUM_ENODADR 100
#endif

#endif /* TOPPERS_ECHONET_CFG_H */

