################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/amigaos.c \
../lib/asyn-ares.c \
../lib/asyn-thread.c \
../lib/base64.c \
../lib/conncache.c \
../lib/connect.c \
../lib/content_encoding.c \
../lib/cookie.c \
../lib/curl_addrinfo.c \
../lib/curl_des.c \
../lib/curl_endian.c \
../lib/curl_fnmatch.c \
../lib/curl_gethostname.c \
../lib/curl_gssapi.c \
../lib/curl_memrchr.c \
../lib/curl_multibyte.c \
../lib/curl_ntlm_core.c \
../lib/curl_ntlm_wb.c \
../lib/curl_rtmp.c \
../lib/curl_sasl.c \
../lib/curl_sspi.c \
../lib/curl_threads.c \
../lib/dict.c \
../lib/dotdot.c \
../lib/easy.c \
../lib/escape.c \
../lib/file.c \
../lib/fileinfo.c \
../lib/formdata.c \
../lib/ftp.c \
../lib/ftplistparser.c \
../lib/getenv.c \
../lib/getinfo.c \
../lib/gopher.c \
../lib/hash.c \
../lib/hmac.c \
../lib/hostasyn.c \
../lib/hostcheck.c \
../lib/hostip.c \
../lib/hostip4.c \
../lib/hostip6.c \
../lib/hostsyn.c \
../lib/http.c \
../lib/http2.c \
../lib/http_chunks.c \
../lib/http_digest.c \
../lib/http_negotiate.c \
../lib/http_ntlm.c \
../lib/http_proxy.c \
../lib/idn_win32.c \
../lib/if2ip.c \
../lib/imap.c \
../lib/inet_ntop.c \
../lib/inet_pton.c \
../lib/krb5.c \
../lib/ldap.c \
../lib/llist.c \
../lib/md4.c \
../lib/md5.c \
../lib/memdebug.c \
../lib/mime.c \
../lib/mprintf.c \
../lib/multi.c \
../lib/netrc.c \
../lib/non-ascii.c \
../lib/nonblock.c \
../lib/nwlib.c \
../lib/nwos.c \
../lib/openldap.c \
../lib/parsedate.c \
../lib/pingpong.c \
../lib/pipeline.c \
../lib/pop3.c \
../lib/progress.c \
../lib/rand.c \
../lib/rtsp.c \
../lib/security.c \
../lib/select.c \
../lib/sendf.c \
../lib/setopt.c \
../lib/sha256.c \
../lib/share.c \
../lib/slist.c \
../lib/smb.c \
../lib/smtp.c \
../lib/socks.c \
../lib/socks_gssapi.c \
../lib/socks_sspi.c \
../lib/speedcheck.c \
../lib/splay.c \
../lib/ssh.c \
../lib/strcase.c \
../lib/strdup.c \
../lib/strerror.c \
../lib/strtok.c \
../lib/strtoofft.c \
../lib/telnet.c \
../lib/tftp.c \
../lib/timeval.c \
../lib/transfer.c \
../lib/url.c \
../lib/version.c \
../lib/warnless.c \
../lib/wildcard.c \
../lib/x509asn1.c 

C_DEPS += \
./lib/amigaos.d \
./lib/asyn-ares.d \
./lib/asyn-thread.d \
./lib/base64.d \
./lib/conncache.d \
./lib/connect.d \
./lib/content_encoding.d \
./lib/cookie.d \
./lib/curl_addrinfo.d \
./lib/curl_des.d \
./lib/curl_endian.d \
./lib/curl_fnmatch.d \
./lib/curl_gethostname.d \
./lib/curl_gssapi.d \
./lib/curl_memrchr.d \
./lib/curl_multibyte.d \
./lib/curl_ntlm_core.d \
./lib/curl_ntlm_wb.d \
./lib/curl_rtmp.d \
./lib/curl_sasl.d \
./lib/curl_sspi.d \
./lib/curl_threads.d \
./lib/dict.d \
./lib/dotdot.d \
./lib/easy.d \
./lib/escape.d \
./lib/file.d \
./lib/fileinfo.d \
./lib/formdata.d \
./lib/ftp.d \
./lib/ftplistparser.d \
./lib/getenv.d \
./lib/getinfo.d \
./lib/gopher.d \
./lib/hash.d \
./lib/hmac.d \
./lib/hostasyn.d \
./lib/hostcheck.d \
./lib/hostip.d \
./lib/hostip4.d \
./lib/hostip6.d \
./lib/hostsyn.d \
./lib/http.d \
./lib/http2.d \
./lib/http_chunks.d \
./lib/http_digest.d \
./lib/http_negotiate.d \
./lib/http_ntlm.d \
./lib/http_proxy.d \
./lib/idn_win32.d \
./lib/if2ip.d \
./lib/imap.d \
./lib/inet_ntop.d \
./lib/inet_pton.d \
./lib/krb5.d \
./lib/ldap.d \
./lib/llist.d \
./lib/md4.d \
./lib/md5.d \
./lib/memdebug.d \
./lib/mime.d \
./lib/mprintf.d \
./lib/multi.d \
./lib/netrc.d \
./lib/non-ascii.d \
./lib/nonblock.d \
./lib/nwlib.d \
./lib/nwos.d \
./lib/openldap.d \
./lib/parsedate.d \
./lib/pingpong.d \
./lib/pipeline.d \
./lib/pop3.d \
./lib/progress.d \
./lib/rand.d \
./lib/rtsp.d \
./lib/security.d \
./lib/select.d \
./lib/sendf.d \
./lib/setopt.d \
./lib/sha256.d \
./lib/share.d \
./lib/slist.d \
./lib/smb.d \
./lib/smtp.d \
./lib/socks.d \
./lib/socks_gssapi.d \
./lib/socks_sspi.d \
./lib/speedcheck.d \
./lib/splay.d \
./lib/ssh.d \
./lib/strcase.d \
./lib/strdup.d \
./lib/strerror.d \
./lib/strtok.d \
./lib/strtoofft.d \
./lib/telnet.d \
./lib/tftp.d \
./lib/timeval.d \
./lib/transfer.d \
./lib/url.d \
./lib/version.d \
./lib/warnless.d \
./lib/wildcard.d \
./lib/x509asn1.d 

OBJS += \
./lib/amigaos.o \
./lib/asyn-ares.o \
./lib/asyn-thread.o \
./lib/base64.o \
./lib/conncache.o \
./lib/connect.o \
./lib/content_encoding.o \
./lib/cookie.o \
./lib/curl_addrinfo.o \
./lib/curl_des.o \
./lib/curl_endian.o \
./lib/curl_fnmatch.o \
./lib/curl_gethostname.o \
./lib/curl_gssapi.o \
./lib/curl_memrchr.o \
./lib/curl_multibyte.o \
./lib/curl_ntlm_core.o \
./lib/curl_ntlm_wb.o \
./lib/curl_rtmp.o \
./lib/curl_sasl.o \
./lib/curl_sspi.o \
./lib/curl_threads.o \
./lib/dict.o \
./lib/dotdot.o \
./lib/easy.o \
./lib/escape.o \
./lib/file.o \
./lib/fileinfo.o \
./lib/formdata.o \
./lib/ftp.o \
./lib/ftplistparser.o \
./lib/getenv.o \
./lib/getinfo.o \
./lib/gopher.o \
./lib/hash.o \
./lib/hmac.o \
./lib/hostasyn.o \
./lib/hostcheck.o \
./lib/hostip.o \
./lib/hostip4.o \
./lib/hostip6.o \
./lib/hostsyn.o \
./lib/http.o \
./lib/http2.o \
./lib/http_chunks.o \
./lib/http_digest.o \
./lib/http_negotiate.o \
./lib/http_ntlm.o \
./lib/http_proxy.o \
./lib/idn_win32.o \
./lib/if2ip.o \
./lib/imap.o \
./lib/inet_ntop.o \
./lib/inet_pton.o \
./lib/krb5.o \
./lib/ldap.o \
./lib/llist.o \
./lib/md4.o \
./lib/md5.o \
./lib/memdebug.o \
./lib/mime.o \
./lib/mprintf.o \
./lib/multi.o \
./lib/netrc.o \
./lib/non-ascii.o \
./lib/nonblock.o \
./lib/nwlib.o \
./lib/nwos.o \
./lib/openldap.o \
./lib/parsedate.o \
./lib/pingpong.o \
./lib/pipeline.o \
./lib/pop3.o \
./lib/progress.o \
./lib/rand.o \
./lib/rtsp.o \
./lib/security.o \
./lib/select.o \
./lib/sendf.o \
./lib/setopt.o \
./lib/sha256.o \
./lib/share.o \
./lib/slist.o \
./lib/smb.o \
./lib/smtp.o \
./lib/socks.o \
./lib/socks_gssapi.o \
./lib/socks_sspi.o \
./lib/speedcheck.o \
./lib/splay.o \
./lib/ssh.o \
./lib/strcase.o \
./lib/strdup.o \
./lib/strerror.o \
./lib/strtok.o \
./lib/strtoofft.o \
./lib/telnet.o \
./lib/tftp.o \
./lib/timeval.o \
./lib/transfer.o \
./lib/url.o \
./lib/version.o \
./lib/warnless.o \
./lib/wildcard.o \
./lib/x509asn1.o 


# Each subdirectory must supply rules for building sources it contributes
lib/%.o: ../lib/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -DHAVE_CONFIG_H -DBUILDING_LIBCURL -DWOLFSSL_USER_SETTINGS -I"C:\trunk_base\trunk\curl-7.57.0\include" -I"C:\trunk_base\trunk\curl-7.57.0\lib" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

