################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/math/__cos.c \
../src/math/__cosdf.c \
../src/math/__cosl.c \
../src/math/__expo2.c \
../src/math/__expo2f.c \
../src/math/__fpclassify.c \
../src/math/__fpclassifyf.c \
../src/math/__fpclassifyl.c \
../src/math/__invtrigl.c \
../src/math/__polevll.c \
../src/math/__rem_pio2.c \
../src/math/__rem_pio2_large.c \
../src/math/__rem_pio2f.c \
../src/math/__rem_pio2l.c \
../src/math/__signbit.c \
../src/math/__signbitf.c \
../src/math/__signbitl.c \
../src/math/__sin.c \
../src/math/__sindf.c \
../src/math/__sinl.c \
../src/math/__tan.c \
../src/math/__tandf.c \
../src/math/__tanl.c \
../src/math/acos.c \
../src/math/acosf.c \
../src/math/acosh.c \
../src/math/acoshf.c \
../src/math/acoshl.c \
../src/math/acosl.c \
../src/math/asin.c \
../src/math/asinf.c \
../src/math/asinh.c \
../src/math/asinhf.c \
../src/math/asinhl.c \
../src/math/asinl.c \
../src/math/atan.c \
../src/math/atan2.c \
../src/math/atan2f.c \
../src/math/atan2l.c \
../src/math/atanf.c \
../src/math/atanh.c \
../src/math/atanhf.c \
../src/math/atanhl.c \
../src/math/atanl.c \
../src/math/cbrt.c \
../src/math/cbrtf.c \
../src/math/cbrtl.c \
../src/math/ceil.c \
../src/math/ceilf.c \
../src/math/ceill.c \
../src/math/copysign.c \
../src/math/copysignf.c \
../src/math/copysignl.c \
../src/math/cos.c \
../src/math/cosf.c \
../src/math/cosh.c \
../src/math/coshf.c \
../src/math/coshl.c \
../src/math/cosl.c \
../src/math/erf.c \
../src/math/erff.c \
../src/math/erfl.c \
../src/math/exp.c \
../src/math/exp10.c \
../src/math/exp10f.c \
../src/math/exp10l.c \
../src/math/exp2.c \
../src/math/exp2f.c \
../src/math/exp2l.c \
../src/math/expf.c \
../src/math/expl.c \
../src/math/expm1.c \
../src/math/expm1f.c \
../src/math/expm1l.c \
../src/math/fabsl.c \
../src/math/fdim.c \
../src/math/fdimf.c \
../src/math/fdiml.c \
../src/math/finite.c \
../src/math/finitef.c \
../src/math/floor.c \
../src/math/floorf.c \
../src/math/floorl.c \
../src/math/fma.c \
../src/math/fmaf.c \
../src/math/fmal.c \
../src/math/fmax.c \
../src/math/fmaxf.c \
../src/math/fmaxl.c \
../src/math/fmin.c \
../src/math/fminf.c \
../src/math/fminl.c \
../src/math/fmod.c \
../src/math/fmodf.c \
../src/math/fmodl.c \
../src/math/frexp.c \
../src/math/frexpf.c \
../src/math/frexpl.c \
../src/math/hypot.c \
../src/math/hypotf.c \
../src/math/hypotl.c \
../src/math/ilogb.c \
../src/math/ilogbf.c \
../src/math/ilogbl.c \
../src/math/j0.c \
../src/math/j0f.c \
../src/math/j1.c \
../src/math/j1f.c \
../src/math/jn.c \
../src/math/jnf.c \
../src/math/ldexp.c \
../src/math/ldexpf.c \
../src/math/ldexpl.c \
../src/math/lgamma.c \
../src/math/lgamma_r.c \
../src/math/lgammaf.c \
../src/math/lgammaf_r.c \
../src/math/lgammal.c \
../src/math/llrint.c \
../src/math/llrintf.c \
../src/math/llrintl.c \
../src/math/llround.c \
../src/math/llroundf.c \
../src/math/llroundl.c \
../src/math/log.c \
../src/math/log10.c \
../src/math/log10f.c \
../src/math/log10l.c \
../src/math/log1p.c \
../src/math/log1pf.c \
../src/math/log1pl.c \
../src/math/log2.c \
../src/math/log2f.c \
../src/math/log2l.c \
../src/math/logb.c \
../src/math/logbf.c \
../src/math/logbl.c \
../src/math/logf.c \
../src/math/logl.c \
../src/math/lrint.c \
../src/math/lrintf.c \
../src/math/lrintl.c \
../src/math/lround.c \
../src/math/lroundf.c \
../src/math/lroundl.c \
../src/math/modf.c \
../src/math/modff.c \
../src/math/modfl.c \
../src/math/nan.c \
../src/math/nanf.c \
../src/math/nanl.c \
../src/math/nearbyint.c \
../src/math/nearbyintf.c \
../src/math/nearbyintl.c \
../src/math/nextafter.c \
../src/math/nextafterf.c \
../src/math/nextafterl.c \
../src/math/nexttoward.c \
../src/math/nexttowardf.c \
../src/math/nexttowardl.c \
../src/math/pow.c \
../src/math/powf.c \
../src/math/powl.c \
../src/math/remainder.c \
../src/math/remainderf.c \
../src/math/remainderl.c \
../src/math/remquo.c \
../src/math/remquof.c \
../src/math/remquol.c \
../src/math/rint.c \
../src/math/rintf.c \
../src/math/rintl.c \
../src/math/round.c \
../src/math/roundf.c \
../src/math/roundl.c \
../src/math/scalb.c \
../src/math/scalbf.c \
../src/math/scalbln.c \
../src/math/scalblnf.c \
../src/math/scalblnl.c \
../src/math/scalbn.c \
../src/math/scalbnf.c \
../src/math/scalbnl.c \
../src/math/signgam.c \
../src/math/significand.c \
../src/math/significandf.c \
../src/math/sin.c \
../src/math/sincos.c \
../src/math/sincosf.c \
../src/math/sincosl.c \
../src/math/sinf.c \
../src/math/sinh.c \
../src/math/sinhf.c \
../src/math/sinhl.c \
../src/math/sinl.c \
../src/math/sqrtl.c \
../src/math/tan.c \
../src/math/tanf.c \
../src/math/tanh.c \
../src/math/tanhf.c \
../src/math/tanhl.c \
../src/math/tanl.c \
../src/math/tgamma.c \
../src/math/tgammaf.c \
../src/math/tgammal.c \
../src/math/trunc.c \
../src/math/truncf.c \
../src/math/truncl.c 

C_DEPS += \
./src/math/__cos.d \
./src/math/__cosdf.d \
./src/math/__cosl.d \
./src/math/__expo2.d \
./src/math/__expo2f.d \
./src/math/__fpclassify.d \
./src/math/__fpclassifyf.d \
./src/math/__fpclassifyl.d \
./src/math/__invtrigl.d \
./src/math/__polevll.d \
./src/math/__rem_pio2.d \
./src/math/__rem_pio2_large.d \
./src/math/__rem_pio2f.d \
./src/math/__rem_pio2l.d \
./src/math/__signbit.d \
./src/math/__signbitf.d \
./src/math/__signbitl.d \
./src/math/__sin.d \
./src/math/__sindf.d \
./src/math/__sinl.d \
./src/math/__tan.d \
./src/math/__tandf.d \
./src/math/__tanl.d \
./src/math/acos.d \
./src/math/acosf.d \
./src/math/acosh.d \
./src/math/acoshf.d \
./src/math/acoshl.d \
./src/math/acosl.d \
./src/math/asin.d \
./src/math/asinf.d \
./src/math/asinh.d \
./src/math/asinhf.d \
./src/math/asinhl.d \
./src/math/asinl.d \
./src/math/atan.d \
./src/math/atan2.d \
./src/math/atan2f.d \
./src/math/atan2l.d \
./src/math/atanf.d \
./src/math/atanh.d \
./src/math/atanhf.d \
./src/math/atanhl.d \
./src/math/atanl.d \
./src/math/cbrt.d \
./src/math/cbrtf.d \
./src/math/cbrtl.d \
./src/math/ceil.d \
./src/math/ceilf.d \
./src/math/ceill.d \
./src/math/copysign.d \
./src/math/copysignf.d \
./src/math/copysignl.d \
./src/math/cos.d \
./src/math/cosf.d \
./src/math/cosh.d \
./src/math/coshf.d \
./src/math/coshl.d \
./src/math/cosl.d \
./src/math/erf.d \
./src/math/erff.d \
./src/math/erfl.d \
./src/math/exp.d \
./src/math/exp10.d \
./src/math/exp10f.d \
./src/math/exp10l.d \
./src/math/exp2.d \
./src/math/exp2f.d \
./src/math/exp2l.d \
./src/math/expf.d \
./src/math/expl.d \
./src/math/expm1.d \
./src/math/expm1f.d \
./src/math/expm1l.d \
./src/math/fabsl.d \
./src/math/fdim.d \
./src/math/fdimf.d \
./src/math/fdiml.d \
./src/math/finite.d \
./src/math/finitef.d \
./src/math/floor.d \
./src/math/floorf.d \
./src/math/floorl.d \
./src/math/fma.d \
./src/math/fmaf.d \
./src/math/fmal.d \
./src/math/fmax.d \
./src/math/fmaxf.d \
./src/math/fmaxl.d \
./src/math/fmin.d \
./src/math/fminf.d \
./src/math/fminl.d \
./src/math/fmod.d \
./src/math/fmodf.d \
./src/math/fmodl.d \
./src/math/frexp.d \
./src/math/frexpf.d \
./src/math/frexpl.d \
./src/math/hypot.d \
./src/math/hypotf.d \
./src/math/hypotl.d \
./src/math/ilogb.d \
./src/math/ilogbf.d \
./src/math/ilogbl.d \
./src/math/j0.d \
./src/math/j0f.d \
./src/math/j1.d \
./src/math/j1f.d \
./src/math/jn.d \
./src/math/jnf.d \
./src/math/ldexp.d \
./src/math/ldexpf.d \
./src/math/ldexpl.d \
./src/math/lgamma.d \
./src/math/lgamma_r.d \
./src/math/lgammaf.d \
./src/math/lgammaf_r.d \
./src/math/lgammal.d \
./src/math/llrint.d \
./src/math/llrintf.d \
./src/math/llrintl.d \
./src/math/llround.d \
./src/math/llroundf.d \
./src/math/llroundl.d \
./src/math/log.d \
./src/math/log10.d \
./src/math/log10f.d \
./src/math/log10l.d \
./src/math/log1p.d \
./src/math/log1pf.d \
./src/math/log1pl.d \
./src/math/log2.d \
./src/math/log2f.d \
./src/math/log2l.d \
./src/math/logb.d \
./src/math/logbf.d \
./src/math/logbl.d \
./src/math/logf.d \
./src/math/logl.d \
./src/math/lrint.d \
./src/math/lrintf.d \
./src/math/lrintl.d \
./src/math/lround.d \
./src/math/lroundf.d \
./src/math/lroundl.d \
./src/math/modf.d \
./src/math/modff.d \
./src/math/modfl.d \
./src/math/nan.d \
./src/math/nanf.d \
./src/math/nanl.d \
./src/math/nearbyint.d \
./src/math/nearbyintf.d \
./src/math/nearbyintl.d \
./src/math/nextafter.d \
./src/math/nextafterf.d \
./src/math/nextafterl.d \
./src/math/nexttoward.d \
./src/math/nexttowardf.d \
./src/math/nexttowardl.d \
./src/math/pow.d \
./src/math/powf.d \
./src/math/powl.d \
./src/math/remainder.d \
./src/math/remainderf.d \
./src/math/remainderl.d \
./src/math/remquo.d \
./src/math/remquof.d \
./src/math/remquol.d \
./src/math/rint.d \
./src/math/rintf.d \
./src/math/rintl.d \
./src/math/round.d \
./src/math/roundf.d \
./src/math/roundl.d \
./src/math/scalb.d \
./src/math/scalbf.d \
./src/math/scalbln.d \
./src/math/scalblnf.d \
./src/math/scalblnl.d \
./src/math/scalbn.d \
./src/math/scalbnf.d \
./src/math/scalbnl.d \
./src/math/signgam.d \
./src/math/significand.d \
./src/math/significandf.d \
./src/math/sin.d \
./src/math/sincos.d \
./src/math/sincosf.d \
./src/math/sincosl.d \
./src/math/sinf.d \
./src/math/sinh.d \
./src/math/sinhf.d \
./src/math/sinhl.d \
./src/math/sinl.d \
./src/math/sqrtl.d \
./src/math/tan.d \
./src/math/tanf.d \
./src/math/tanh.d \
./src/math/tanhf.d \
./src/math/tanhl.d \
./src/math/tanl.d \
./src/math/tgamma.d \
./src/math/tgammaf.d \
./src/math/tgammal.d \
./src/math/trunc.d \
./src/math/truncf.d \
./src/math/truncl.d 

OBJS += \
./src/math/__cos.o \
./src/math/__cosdf.o \
./src/math/__cosl.o \
./src/math/__expo2.o \
./src/math/__expo2f.o \
./src/math/__fpclassify.o \
./src/math/__fpclassifyf.o \
./src/math/__fpclassifyl.o \
./src/math/__invtrigl.o \
./src/math/__polevll.o \
./src/math/__rem_pio2.o \
./src/math/__rem_pio2_large.o \
./src/math/__rem_pio2f.o \
./src/math/__rem_pio2l.o \
./src/math/__signbit.o \
./src/math/__signbitf.o \
./src/math/__signbitl.o \
./src/math/__sin.o \
./src/math/__sindf.o \
./src/math/__sinl.o \
./src/math/__tan.o \
./src/math/__tandf.o \
./src/math/__tanl.o \
./src/math/acos.o \
./src/math/acosf.o \
./src/math/acosh.o \
./src/math/acoshf.o \
./src/math/acoshl.o \
./src/math/acosl.o \
./src/math/asin.o \
./src/math/asinf.o \
./src/math/asinh.o \
./src/math/asinhf.o \
./src/math/asinhl.o \
./src/math/asinl.o \
./src/math/atan.o \
./src/math/atan2.o \
./src/math/atan2f.o \
./src/math/atan2l.o \
./src/math/atanf.o \
./src/math/atanh.o \
./src/math/atanhf.o \
./src/math/atanhl.o \
./src/math/atanl.o \
./src/math/cbrt.o \
./src/math/cbrtf.o \
./src/math/cbrtl.o \
./src/math/ceil.o \
./src/math/ceilf.o \
./src/math/ceill.o \
./src/math/copysign.o \
./src/math/copysignf.o \
./src/math/copysignl.o \
./src/math/cos.o \
./src/math/cosf.o \
./src/math/cosh.o \
./src/math/coshf.o \
./src/math/coshl.o \
./src/math/cosl.o \
./src/math/erf.o \
./src/math/erff.o \
./src/math/erfl.o \
./src/math/exp.o \
./src/math/exp10.o \
./src/math/exp10f.o \
./src/math/exp10l.o \
./src/math/exp2.o \
./src/math/exp2f.o \
./src/math/exp2l.o \
./src/math/expf.o \
./src/math/expl.o \
./src/math/expm1.o \
./src/math/expm1f.o \
./src/math/expm1l.o \
./src/math/fabsl.o \
./src/math/fdim.o \
./src/math/fdimf.o \
./src/math/fdiml.o \
./src/math/finite.o \
./src/math/finitef.o \
./src/math/floor.o \
./src/math/floorf.o \
./src/math/floorl.o \
./src/math/fma.o \
./src/math/fmaf.o \
./src/math/fmal.o \
./src/math/fmax.o \
./src/math/fmaxf.o \
./src/math/fmaxl.o \
./src/math/fmin.o \
./src/math/fminf.o \
./src/math/fminl.o \
./src/math/fmod.o \
./src/math/fmodf.o \
./src/math/fmodl.o \
./src/math/frexp.o \
./src/math/frexpf.o \
./src/math/frexpl.o \
./src/math/hypot.o \
./src/math/hypotf.o \
./src/math/hypotl.o \
./src/math/ilogb.o \
./src/math/ilogbf.o \
./src/math/ilogbl.o \
./src/math/j0.o \
./src/math/j0f.o \
./src/math/j1.o \
./src/math/j1f.o \
./src/math/jn.o \
./src/math/jnf.o \
./src/math/ldexp.o \
./src/math/ldexpf.o \
./src/math/ldexpl.o \
./src/math/lgamma.o \
./src/math/lgamma_r.o \
./src/math/lgammaf.o \
./src/math/lgammaf_r.o \
./src/math/lgammal.o \
./src/math/llrint.o \
./src/math/llrintf.o \
./src/math/llrintl.o \
./src/math/llround.o \
./src/math/llroundf.o \
./src/math/llroundl.o \
./src/math/log.o \
./src/math/log10.o \
./src/math/log10f.o \
./src/math/log10l.o \
./src/math/log1p.o \
./src/math/log1pf.o \
./src/math/log1pl.o \
./src/math/log2.o \
./src/math/log2f.o \
./src/math/log2l.o \
./src/math/logb.o \
./src/math/logbf.o \
./src/math/logbl.o \
./src/math/logf.o \
./src/math/logl.o \
./src/math/lrint.o \
./src/math/lrintf.o \
./src/math/lrintl.o \
./src/math/lround.o \
./src/math/lroundf.o \
./src/math/lroundl.o \
./src/math/modf.o \
./src/math/modff.o \
./src/math/modfl.o \
./src/math/nan.o \
./src/math/nanf.o \
./src/math/nanl.o \
./src/math/nearbyint.o \
./src/math/nearbyintf.o \
./src/math/nearbyintl.o \
./src/math/nextafter.o \
./src/math/nextafterf.o \
./src/math/nextafterl.o \
./src/math/nexttoward.o \
./src/math/nexttowardf.o \
./src/math/nexttowardl.o \
./src/math/pow.o \
./src/math/powf.o \
./src/math/powl.o \
./src/math/remainder.o \
./src/math/remainderf.o \
./src/math/remainderl.o \
./src/math/remquo.o \
./src/math/remquof.o \
./src/math/remquol.o \
./src/math/rint.o \
./src/math/rintf.o \
./src/math/rintl.o \
./src/math/round.o \
./src/math/roundf.o \
./src/math/roundl.o \
./src/math/scalb.o \
./src/math/scalbf.o \
./src/math/scalbln.o \
./src/math/scalblnf.o \
./src/math/scalblnl.o \
./src/math/scalbn.o \
./src/math/scalbnf.o \
./src/math/scalbnl.o \
./src/math/signgam.o \
./src/math/significand.o \
./src/math/significandf.o \
./src/math/sin.o \
./src/math/sincos.o \
./src/math/sincosf.o \
./src/math/sincosl.o \
./src/math/sinf.o \
./src/math/sinh.o \
./src/math/sinhf.o \
./src/math/sinhl.o \
./src/math/sinl.o \
./src/math/sqrtl.o \
./src/math/tan.o \
./src/math/tanf.o \
./src/math/tanh.o \
./src/math/tanhf.o \
./src/math/tanhl.o \
./src/math/tanl.o \
./src/math/tgamma.o \
./src/math/tgammaf.o \
./src/math/tgammal.o \
./src/math/trunc.o \
./src/math/truncf.o \
./src/math/truncl.o 


# Each subdirectory must supply rules for building sources it contributes
src/math/%.o: ../src/math/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

