################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/thread/__futex.c \
../src/thread/__lock.c \
../src/thread/__syscall_cp.c \
../src/thread/__timedwait.c \
../src/thread/__tls_get_addr.c \
../src/thread/__unmapself.c \
../src/thread/__wait.c \
../src/thread/call_once.c \
../src/thread/clone.c \
../src/thread/cnd_broadcast.c \
../src/thread/cnd_destroy.c \
../src/thread/cnd_init.c \
../src/thread/cnd_signal.c \
../src/thread/cnd_timedwait.c \
../src/thread/cnd_wait.c \
../src/thread/lock_ptc.c \
../src/thread/mtx_destroy.c \
../src/thread/mtx_init.c \
../src/thread/mtx_lock.c \
../src/thread/mtx_timedlock.c \
../src/thread/mtx_trylock.c \
../src/thread/mtx_unlock.c \
../src/thread/pthread_atfork.c \
../src/thread/pthread_attr_destroy.c \
../src/thread/pthread_attr_get.c \
../src/thread/pthread_attr_init.c \
../src/thread/pthread_attr_setdetachstate.c \
../src/thread/pthread_attr_setguardsize.c \
../src/thread/pthread_attr_setinheritsched.c \
../src/thread/pthread_attr_setschedparam.c \
../src/thread/pthread_attr_setschedpolicy.c \
../src/thread/pthread_attr_setscope.c \
../src/thread/pthread_attr_setstack.c \
../src/thread/pthread_attr_setstacksize.c \
../src/thread/pthread_barrier_destroy.c \
../src/thread/pthread_barrier_init.c \
../src/thread/pthread_barrier_wait.c \
../src/thread/pthread_barrierattr_destroy.c \
../src/thread/pthread_barrierattr_init.c \
../src/thread/pthread_barrierattr_setpshared.c \
../src/thread/pthread_cancel.c \
../src/thread/pthread_cleanup_push.c \
../src/thread/pthread_cond_broadcast.c \
../src/thread/pthread_cond_destroy.c \
../src/thread/pthread_cond_init.c \
../src/thread/pthread_cond_signal.c \
../src/thread/pthread_cond_timedwait.c \
../src/thread/pthread_cond_wait.c \
../src/thread/pthread_condattr_destroy.c \
../src/thread/pthread_condattr_init.c \
../src/thread/pthread_condattr_setclock.c \
../src/thread/pthread_condattr_setpshared.c \
../src/thread/pthread_create.c \
../src/thread/pthread_detach.c \
../src/thread/pthread_equal.c \
../src/thread/pthread_getattr_np.c \
../src/thread/pthread_getconcurrency.c \
../src/thread/pthread_getcpuclockid.c \
../src/thread/pthread_getschedparam.c \
../src/thread/pthread_getspecific.c \
../src/thread/pthread_join.c \
../src/thread/pthread_key_create.c \
../src/thread/pthread_kill.c \
../src/thread/pthread_mutex_consistent.c \
../src/thread/pthread_mutex_destroy.c \
../src/thread/pthread_mutex_getprioceiling.c \
../src/thread/pthread_mutex_init.c \
../src/thread/pthread_mutex_lock.c \
../src/thread/pthread_mutex_setprioceiling.c \
../src/thread/pthread_mutex_timedlock.c \
../src/thread/pthread_mutex_trylock.c \
../src/thread/pthread_mutex_unlock.c \
../src/thread/pthread_mutexattr_destroy.c \
../src/thread/pthread_mutexattr_init.c \
../src/thread/pthread_mutexattr_setprotocol.c \
../src/thread/pthread_mutexattr_setpshared.c \
../src/thread/pthread_mutexattr_setrobust.c \
../src/thread/pthread_mutexattr_settype.c \
../src/thread/pthread_once.c \
../src/thread/pthread_rwlock_destroy.c \
../src/thread/pthread_rwlock_init.c \
../src/thread/pthread_rwlock_rdlock.c \
../src/thread/pthread_rwlock_timedrdlock.c \
../src/thread/pthread_rwlock_timedwrlock.c \
../src/thread/pthread_rwlock_tryrdlock.c \
../src/thread/pthread_rwlock_trywrlock.c \
../src/thread/pthread_rwlock_unlock.c \
../src/thread/pthread_rwlock_wrlock.c \
../src/thread/pthread_rwlockattr_destroy.c \
../src/thread/pthread_rwlockattr_init.c \
../src/thread/pthread_rwlockattr_setpshared.c \
../src/thread/pthread_self.c \
../src/thread/pthread_setattr_default_np.c \
../src/thread/pthread_setcancelstate.c \
../src/thread/pthread_setcanceltype.c \
../src/thread/pthread_setconcurrency.c \
../src/thread/pthread_setname_np.c \
../src/thread/pthread_setschedparam.c \
../src/thread/pthread_setschedprio.c \
../src/thread/pthread_setspecific.c \
../src/thread/pthread_sigmask.c \
../src/thread/pthread_spin_destroy.c \
../src/thread/pthread_spin_init.c \
../src/thread/pthread_spin_lock.c \
../src/thread/pthread_spin_trylock.c \
../src/thread/pthread_spin_unlock.c \
../src/thread/pthread_testcancel.c \
../src/thread/sem_destroy.c \
../src/thread/sem_getvalue.c \
../src/thread/sem_init.c \
../src/thread/sem_open.c \
../src/thread/sem_post.c \
../src/thread/sem_timedwait.c \
../src/thread/sem_trywait.c \
../src/thread/sem_unlink.c \
../src/thread/sem_wait.c \
../src/thread/synccall.c \
../src/thread/syscall_cp.c \
../src/thread/thrd_create.c \
../src/thread/thrd_exit.c \
../src/thread/thrd_join.c \
../src/thread/thrd_sleep.c \
../src/thread/thrd_yield.c \
../src/thread/tls.c \
../src/thread/tss_create.c \
../src/thread/tss_delete.c \
../src/thread/tss_set.c \
../src/thread/vmlock.c 

C_DEPS += \
./src/thread/__futex.d \
./src/thread/__lock.d \
./src/thread/__syscall_cp.d \
./src/thread/__timedwait.d \
./src/thread/__tls_get_addr.d \
./src/thread/__unmapself.d \
./src/thread/__wait.d \
./src/thread/call_once.d \
./src/thread/clone.d \
./src/thread/cnd_broadcast.d \
./src/thread/cnd_destroy.d \
./src/thread/cnd_init.d \
./src/thread/cnd_signal.d \
./src/thread/cnd_timedwait.d \
./src/thread/cnd_wait.d \
./src/thread/lock_ptc.d \
./src/thread/mtx_destroy.d \
./src/thread/mtx_init.d \
./src/thread/mtx_lock.d \
./src/thread/mtx_timedlock.d \
./src/thread/mtx_trylock.d \
./src/thread/mtx_unlock.d \
./src/thread/pthread_atfork.d \
./src/thread/pthread_attr_destroy.d \
./src/thread/pthread_attr_get.d \
./src/thread/pthread_attr_init.d \
./src/thread/pthread_attr_setdetachstate.d \
./src/thread/pthread_attr_setguardsize.d \
./src/thread/pthread_attr_setinheritsched.d \
./src/thread/pthread_attr_setschedparam.d \
./src/thread/pthread_attr_setschedpolicy.d \
./src/thread/pthread_attr_setscope.d \
./src/thread/pthread_attr_setstack.d \
./src/thread/pthread_attr_setstacksize.d \
./src/thread/pthread_barrier_destroy.d \
./src/thread/pthread_barrier_init.d \
./src/thread/pthread_barrier_wait.d \
./src/thread/pthread_barrierattr_destroy.d \
./src/thread/pthread_barrierattr_init.d \
./src/thread/pthread_barrierattr_setpshared.d \
./src/thread/pthread_cancel.d \
./src/thread/pthread_cleanup_push.d \
./src/thread/pthread_cond_broadcast.d \
./src/thread/pthread_cond_destroy.d \
./src/thread/pthread_cond_init.d \
./src/thread/pthread_cond_signal.d \
./src/thread/pthread_cond_timedwait.d \
./src/thread/pthread_cond_wait.d \
./src/thread/pthread_condattr_destroy.d \
./src/thread/pthread_condattr_init.d \
./src/thread/pthread_condattr_setclock.d \
./src/thread/pthread_condattr_setpshared.d \
./src/thread/pthread_create.d \
./src/thread/pthread_detach.d \
./src/thread/pthread_equal.d \
./src/thread/pthread_getattr_np.d \
./src/thread/pthread_getconcurrency.d \
./src/thread/pthread_getcpuclockid.d \
./src/thread/pthread_getschedparam.d \
./src/thread/pthread_getspecific.d \
./src/thread/pthread_join.d \
./src/thread/pthread_key_create.d \
./src/thread/pthread_kill.d \
./src/thread/pthread_mutex_consistent.d \
./src/thread/pthread_mutex_destroy.d \
./src/thread/pthread_mutex_getprioceiling.d \
./src/thread/pthread_mutex_init.d \
./src/thread/pthread_mutex_lock.d \
./src/thread/pthread_mutex_setprioceiling.d \
./src/thread/pthread_mutex_timedlock.d \
./src/thread/pthread_mutex_trylock.d \
./src/thread/pthread_mutex_unlock.d \
./src/thread/pthread_mutexattr_destroy.d \
./src/thread/pthread_mutexattr_init.d \
./src/thread/pthread_mutexattr_setprotocol.d \
./src/thread/pthread_mutexattr_setpshared.d \
./src/thread/pthread_mutexattr_setrobust.d \
./src/thread/pthread_mutexattr_settype.d \
./src/thread/pthread_once.d \
./src/thread/pthread_rwlock_destroy.d \
./src/thread/pthread_rwlock_init.d \
./src/thread/pthread_rwlock_rdlock.d \
./src/thread/pthread_rwlock_timedrdlock.d \
./src/thread/pthread_rwlock_timedwrlock.d \
./src/thread/pthread_rwlock_tryrdlock.d \
./src/thread/pthread_rwlock_trywrlock.d \
./src/thread/pthread_rwlock_unlock.d \
./src/thread/pthread_rwlock_wrlock.d \
./src/thread/pthread_rwlockattr_destroy.d \
./src/thread/pthread_rwlockattr_init.d \
./src/thread/pthread_rwlockattr_setpshared.d \
./src/thread/pthread_self.d \
./src/thread/pthread_setattr_default_np.d \
./src/thread/pthread_setcancelstate.d \
./src/thread/pthread_setcanceltype.d \
./src/thread/pthread_setconcurrency.d \
./src/thread/pthread_setname_np.d \
./src/thread/pthread_setschedparam.d \
./src/thread/pthread_setschedprio.d \
./src/thread/pthread_setspecific.d \
./src/thread/pthread_sigmask.d \
./src/thread/pthread_spin_destroy.d \
./src/thread/pthread_spin_init.d \
./src/thread/pthread_spin_lock.d \
./src/thread/pthread_spin_trylock.d \
./src/thread/pthread_spin_unlock.d \
./src/thread/pthread_testcancel.d \
./src/thread/sem_destroy.d \
./src/thread/sem_getvalue.d \
./src/thread/sem_init.d \
./src/thread/sem_open.d \
./src/thread/sem_post.d \
./src/thread/sem_timedwait.d \
./src/thread/sem_trywait.d \
./src/thread/sem_unlink.d \
./src/thread/sem_wait.d \
./src/thread/synccall.d \
./src/thread/syscall_cp.d \
./src/thread/thrd_create.d \
./src/thread/thrd_exit.d \
./src/thread/thrd_join.d \
./src/thread/thrd_sleep.d \
./src/thread/thrd_yield.d \
./src/thread/tls.d \
./src/thread/tss_create.d \
./src/thread/tss_delete.d \
./src/thread/tss_set.d \
./src/thread/vmlock.d 

OBJS += \
./src/thread/__futex.o \
./src/thread/__lock.o \
./src/thread/__syscall_cp.o \
./src/thread/__timedwait.o \
./src/thread/__tls_get_addr.o \
./src/thread/__unmapself.o \
./src/thread/__wait.o \
./src/thread/call_once.o \
./src/thread/clone.o \
./src/thread/cnd_broadcast.o \
./src/thread/cnd_destroy.o \
./src/thread/cnd_init.o \
./src/thread/cnd_signal.o \
./src/thread/cnd_timedwait.o \
./src/thread/cnd_wait.o \
./src/thread/lock_ptc.o \
./src/thread/mtx_destroy.o \
./src/thread/mtx_init.o \
./src/thread/mtx_lock.o \
./src/thread/mtx_timedlock.o \
./src/thread/mtx_trylock.o \
./src/thread/mtx_unlock.o \
./src/thread/pthread_atfork.o \
./src/thread/pthread_attr_destroy.o \
./src/thread/pthread_attr_get.o \
./src/thread/pthread_attr_init.o \
./src/thread/pthread_attr_setdetachstate.o \
./src/thread/pthread_attr_setguardsize.o \
./src/thread/pthread_attr_setinheritsched.o \
./src/thread/pthread_attr_setschedparam.o \
./src/thread/pthread_attr_setschedpolicy.o \
./src/thread/pthread_attr_setscope.o \
./src/thread/pthread_attr_setstack.o \
./src/thread/pthread_attr_setstacksize.o \
./src/thread/pthread_barrier_destroy.o \
./src/thread/pthread_barrier_init.o \
./src/thread/pthread_barrier_wait.o \
./src/thread/pthread_barrierattr_destroy.o \
./src/thread/pthread_barrierattr_init.o \
./src/thread/pthread_barrierattr_setpshared.o \
./src/thread/pthread_cancel.o \
./src/thread/pthread_cleanup_push.o \
./src/thread/pthread_cond_broadcast.o \
./src/thread/pthread_cond_destroy.o \
./src/thread/pthread_cond_init.o \
./src/thread/pthread_cond_signal.o \
./src/thread/pthread_cond_timedwait.o \
./src/thread/pthread_cond_wait.o \
./src/thread/pthread_condattr_destroy.o \
./src/thread/pthread_condattr_init.o \
./src/thread/pthread_condattr_setclock.o \
./src/thread/pthread_condattr_setpshared.o \
./src/thread/pthread_create.o \
./src/thread/pthread_detach.o \
./src/thread/pthread_equal.o \
./src/thread/pthread_getattr_np.o \
./src/thread/pthread_getconcurrency.o \
./src/thread/pthread_getcpuclockid.o \
./src/thread/pthread_getschedparam.o \
./src/thread/pthread_getspecific.o \
./src/thread/pthread_join.o \
./src/thread/pthread_key_create.o \
./src/thread/pthread_kill.o \
./src/thread/pthread_mutex_consistent.o \
./src/thread/pthread_mutex_destroy.o \
./src/thread/pthread_mutex_getprioceiling.o \
./src/thread/pthread_mutex_init.o \
./src/thread/pthread_mutex_lock.o \
./src/thread/pthread_mutex_setprioceiling.o \
./src/thread/pthread_mutex_timedlock.o \
./src/thread/pthread_mutex_trylock.o \
./src/thread/pthread_mutex_unlock.o \
./src/thread/pthread_mutexattr_destroy.o \
./src/thread/pthread_mutexattr_init.o \
./src/thread/pthread_mutexattr_setprotocol.o \
./src/thread/pthread_mutexattr_setpshared.o \
./src/thread/pthread_mutexattr_setrobust.o \
./src/thread/pthread_mutexattr_settype.o \
./src/thread/pthread_once.o \
./src/thread/pthread_rwlock_destroy.o \
./src/thread/pthread_rwlock_init.o \
./src/thread/pthread_rwlock_rdlock.o \
./src/thread/pthread_rwlock_timedrdlock.o \
./src/thread/pthread_rwlock_timedwrlock.o \
./src/thread/pthread_rwlock_tryrdlock.o \
./src/thread/pthread_rwlock_trywrlock.o \
./src/thread/pthread_rwlock_unlock.o \
./src/thread/pthread_rwlock_wrlock.o \
./src/thread/pthread_rwlockattr_destroy.o \
./src/thread/pthread_rwlockattr_init.o \
./src/thread/pthread_rwlockattr_setpshared.o \
./src/thread/pthread_self.o \
./src/thread/pthread_setattr_default_np.o \
./src/thread/pthread_setcancelstate.o \
./src/thread/pthread_setcanceltype.o \
./src/thread/pthread_setconcurrency.o \
./src/thread/pthread_setname_np.o \
./src/thread/pthread_setschedparam.o \
./src/thread/pthread_setschedprio.o \
./src/thread/pthread_setspecific.o \
./src/thread/pthread_sigmask.o \
./src/thread/pthread_spin_destroy.o \
./src/thread/pthread_spin_init.o \
./src/thread/pthread_spin_lock.o \
./src/thread/pthread_spin_trylock.o \
./src/thread/pthread_spin_unlock.o \
./src/thread/pthread_testcancel.o \
./src/thread/sem_destroy.o \
./src/thread/sem_getvalue.o \
./src/thread/sem_init.o \
./src/thread/sem_open.o \
./src/thread/sem_post.o \
./src/thread/sem_timedwait.o \
./src/thread/sem_trywait.o \
./src/thread/sem_unlink.o \
./src/thread/sem_wait.o \
./src/thread/synccall.o \
./src/thread/syscall_cp.o \
./src/thread/thrd_create.o \
./src/thread/thrd_exit.o \
./src/thread/thrd_join.o \
./src/thread/thrd_sleep.o \
./src/thread/thrd_yield.o \
./src/thread/tls.o \
./src/thread/tss_create.o \
./src/thread/tss_delete.o \
./src/thread/tss_set.o \
./src/thread/vmlock.o 


# Each subdirectory must supply rules for building sources it contributes
src/thread/%.o: ../src/thread/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

