/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tECNLGeneralLighting_templ.c => src/tECNLGeneralLighting.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cGeneralLighting signature: sGeneralLighting context:task
 *   void           cGeneralLighting_setLightingModeSetting_Automatic( );
 *   void           cGeneralLighting_setLightingModeSetting_NormalLighting( );
 *   void           cGeneralLighting_setLightingModeSetting_NightLighting( );
 *   void           cGeneralLighting_setLightingModeSetting_ColorLighting( );
 *   void           cGeneralLighting_getLightingModeSetting_Automatic( );
 *   void           cGeneralLighting_getLightingModeSetting_NormalLighting( );
 *   void           cGeneralLighting_getLightingModeSetting_NightLighting( );
 *   void           cGeneralLighting_getLightingModeSetting_ColorLighting( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tECNLGeneralLighting_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eTaskBody
 * entry port: eTaskBody
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eTaskBody_main
 * name:         eTaskBody_main
 * global_name:  tECNLGeneralLighting_eTaskBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eTaskBody_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
