/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tGeneralLighting_templ.c => src/tGeneralLighting.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tGeneralLighting_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eGeneralLighting
 * entry port: eGeneralLighting
 * signature:  sGeneralLighting
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_Automatic
 * name:         eGeneralLighting_setLightingModeSetting_Automatic
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_Automatic
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_Automatic(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_NormalLighting
 * name:         eGeneralLighting_setLightingModeSetting_NormalLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_NormalLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_NormalLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_NightLighting
 * name:         eGeneralLighting_setLightingModeSetting_NightLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_NightLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_NightLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_setLightingModeSetting_ColorLighting
 * name:         eGeneralLighting_setLightingModeSetting_ColorLighting
 * global_name:  tGeneralLighting_eGeneralLighting_setLightingModeSetting_ColorLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_setLightingModeSetting_ColorLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_Automatic
 * name:         eGeneralLighting_getLightingModeSetting_Automatic
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_Automatic
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_Automatic(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_NormalLighting
 * name:         eGeneralLighting_getLightingModeSetting_NormalLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_NormalLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_NormalLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_NightLighting
 * name:         eGeneralLighting_getLightingModeSetting_NightLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_NightLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_NightLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eGeneralLighting_getLightingModeSetting_ColorLighting
 * name:         eGeneralLighting_getLightingModeSetting_ColorLighting
 * global_name:  tGeneralLighting_eGeneralLighting_getLightingModeSetting_ColorLighting
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGeneralLighting_getLightingModeSetting_ColorLighting(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
