################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/complex/__cexp.c \
../src/complex/__cexpf.c \
../src/complex/cabs.c \
../src/complex/cabsf.c \
../src/complex/cabsl.c \
../src/complex/cacos.c \
../src/complex/cacosf.c \
../src/complex/cacosh.c \
../src/complex/cacoshf.c \
../src/complex/cacoshl.c \
../src/complex/cacosl.c \
../src/complex/carg.c \
../src/complex/cargf.c \
../src/complex/cargl.c \
../src/complex/casin.c \
../src/complex/casinf.c \
../src/complex/casinh.c \
../src/complex/casinhf.c \
../src/complex/casinhl.c \
../src/complex/casinl.c \
../src/complex/catan.c \
../src/complex/catanf.c \
../src/complex/catanh.c \
../src/complex/catanhf.c \
../src/complex/catanhl.c \
../src/complex/catanl.c \
../src/complex/ccos.c \
../src/complex/ccosf.c \
../src/complex/ccosh.c \
../src/complex/ccoshf.c \
../src/complex/ccoshl.c \
../src/complex/ccosl.c \
../src/complex/cexp.c \
../src/complex/cexpf.c \
../src/complex/cexpl.c \
../src/complex/cimag.c \
../src/complex/cimagf.c \
../src/complex/cimagl.c \
../src/complex/clog.c \
../src/complex/clogf.c \
../src/complex/clogl.c \
../src/complex/conj.c \
../src/complex/conjf.c \
../src/complex/conjl.c \
../src/complex/cpow.c \
../src/complex/cpowf.c \
../src/complex/cpowl.c \
../src/complex/cproj.c \
../src/complex/cprojf.c \
../src/complex/cprojl.c \
../src/complex/creal.c \
../src/complex/crealf.c \
../src/complex/creall.c \
../src/complex/csin.c \
../src/complex/csinf.c \
../src/complex/csinh.c \
../src/complex/csinhf.c \
../src/complex/csinhl.c \
../src/complex/csinl.c \
../src/complex/csqrt.c \
../src/complex/csqrtf.c \
../src/complex/csqrtl.c \
../src/complex/ctan.c \
../src/complex/ctanf.c \
../src/complex/ctanh.c \
../src/complex/ctanhf.c \
../src/complex/ctanhl.c \
../src/complex/ctanl.c 

C_DEPS += \
./src/complex/__cexp.d \
./src/complex/__cexpf.d \
./src/complex/cabs.d \
./src/complex/cabsf.d \
./src/complex/cabsl.d \
./src/complex/cacos.d \
./src/complex/cacosf.d \
./src/complex/cacosh.d \
./src/complex/cacoshf.d \
./src/complex/cacoshl.d \
./src/complex/cacosl.d \
./src/complex/carg.d \
./src/complex/cargf.d \
./src/complex/cargl.d \
./src/complex/casin.d \
./src/complex/casinf.d \
./src/complex/casinh.d \
./src/complex/casinhf.d \
./src/complex/casinhl.d \
./src/complex/casinl.d \
./src/complex/catan.d \
./src/complex/catanf.d \
./src/complex/catanh.d \
./src/complex/catanhf.d \
./src/complex/catanhl.d \
./src/complex/catanl.d \
./src/complex/ccos.d \
./src/complex/ccosf.d \
./src/complex/ccosh.d \
./src/complex/ccoshf.d \
./src/complex/ccoshl.d \
./src/complex/ccosl.d \
./src/complex/cexp.d \
./src/complex/cexpf.d \
./src/complex/cexpl.d \
./src/complex/cimag.d \
./src/complex/cimagf.d \
./src/complex/cimagl.d \
./src/complex/clog.d \
./src/complex/clogf.d \
./src/complex/clogl.d \
./src/complex/conj.d \
./src/complex/conjf.d \
./src/complex/conjl.d \
./src/complex/cpow.d \
./src/complex/cpowf.d \
./src/complex/cpowl.d \
./src/complex/cproj.d \
./src/complex/cprojf.d \
./src/complex/cprojl.d \
./src/complex/creal.d \
./src/complex/crealf.d \
./src/complex/creall.d \
./src/complex/csin.d \
./src/complex/csinf.d \
./src/complex/csinh.d \
./src/complex/csinhf.d \
./src/complex/csinhl.d \
./src/complex/csinl.d \
./src/complex/csqrt.d \
./src/complex/csqrtf.d \
./src/complex/csqrtl.d \
./src/complex/ctan.d \
./src/complex/ctanf.d \
./src/complex/ctanh.d \
./src/complex/ctanhf.d \
./src/complex/ctanhl.d \
./src/complex/ctanl.d 

OBJS += \
./src/complex/__cexp.o \
./src/complex/__cexpf.o \
./src/complex/cabs.o \
./src/complex/cabsf.o \
./src/complex/cabsl.o \
./src/complex/cacos.o \
./src/complex/cacosf.o \
./src/complex/cacosh.o \
./src/complex/cacoshf.o \
./src/complex/cacoshl.o \
./src/complex/cacosl.o \
./src/complex/carg.o \
./src/complex/cargf.o \
./src/complex/cargl.o \
./src/complex/casin.o \
./src/complex/casinf.o \
./src/complex/casinh.o \
./src/complex/casinhf.o \
./src/complex/casinhl.o \
./src/complex/casinl.o \
./src/complex/catan.o \
./src/complex/catanf.o \
./src/complex/catanh.o \
./src/complex/catanhf.o \
./src/complex/catanhl.o \
./src/complex/catanl.o \
./src/complex/ccos.o \
./src/complex/ccosf.o \
./src/complex/ccosh.o \
./src/complex/ccoshf.o \
./src/complex/ccoshl.o \
./src/complex/ccosl.o \
./src/complex/cexp.o \
./src/complex/cexpf.o \
./src/complex/cexpl.o \
./src/complex/cimag.o \
./src/complex/cimagf.o \
./src/complex/cimagl.o \
./src/complex/clog.o \
./src/complex/clogf.o \
./src/complex/clogl.o \
./src/complex/conj.o \
./src/complex/conjf.o \
./src/complex/conjl.o \
./src/complex/cpow.o \
./src/complex/cpowf.o \
./src/complex/cpowl.o \
./src/complex/cproj.o \
./src/complex/cprojf.o \
./src/complex/cprojl.o \
./src/complex/creal.o \
./src/complex/crealf.o \
./src/complex/creall.o \
./src/complex/csin.o \
./src/complex/csinf.o \
./src/complex/csinh.o \
./src/complex/csinhf.o \
./src/complex/csinhl.o \
./src/complex/csinl.o \
./src/complex/csqrt.o \
./src/complex/csqrtf.o \
./src/complex/csqrtl.o \
./src/complex/ctan.o \
./src/complex/ctanf.o \
./src/complex/ctanh.o \
./src/complex/ctanhf.o \
./src/complex/ctanhl.o \
./src/complex/ctanl.o 


# Each subdirectory must supply rules for building sources it contributes
src/complex/%.o: ../src/complex/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

