#ifndef __BTSTACK_CONFIG
#define __BTSTACK_CONFIG

#define EMBEDDED
#define HAVE_MALLOC

//#define HAVE_BLE
#define HAVE_BNEP

#define HAVE_INIT_SCRIPT
#define HAVE_BZERO
#define HAVE_TICK

#define HAVE_EHCILL
#define HAVE_SDP_EXTRA_QUERIES

//#define ENABLE_LOG_DEBUG
//#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
//#define SDP_DES_DUMP
//#define PRIx32 "lx"

#define HCI_ACL_PAYLOAD_SIZE 1710

#if 1
#define MAX_SPP_CONNECTIONS 1
#define MAX_PAN_CONNECTIONS 4
#define MAX_NO_GATT_CLIENTS 0
#define MAX_NO_GATT_SUBCLIENTS 0
#define MAX_NO_HCI_CONNECTIONS (1 + MAX_SPP_CONNECTIONS + MAX_PAN_CONNECTIONS)
#define MAX_NO_L2CAP_SERVICES  3//SDP+RFCOMM+BNEP
#define MAX_NO_L2CAP_CHANNELS  (1 + MAX_SPP_CONNECTIONS + MAX_PAN_CONNECTIONS)
#define MAX_NO_RFCOMM_MULTIPLEXERS MAX_SPP_CONNECTIONS
#define MAX_NO_RFCOMM_SERVICES 1
#define MAX_NO_RFCOMM_CHANNELS MAX_SPP_CONNECTIONS
#define MAX_NO_DB_MEM_DEVICE_LINK_KEYS  4
#define MAX_NO_DB_MEM_DEVICE_NAMES 4
#define MAX_NO_DB_MEM_SERVICES 4
#define MAX_NO_BNEP_SERVICES 1
#define MAX_NO_BNEP_CHANNELS MAX_PAN_CONNECTIONS
#else
#define MAX_SPP_CONNECTIONS 3
#define MAX_NO_HCI_CONNECTIONS MAX_SPP_CONNECTIONS
#define MAX_NO_GATT_CLIENTS 0
#define MAX_NO_GATT_SUBCLIENTS 0
#define MAX_NO_L2CAP_SERVICES  2
#define MAX_NO_L2CAP_CHANNELS  (1+MAX_SPP_CONNECTIONS)
#define MAX_NO_RFCOMM_MULTIPLEXERS MAX_SPP_CONNECTIONS
#define MAX_NO_RFCOMM_SERVICES 1
#define MAX_NO_RFCOMM_CHANNELS MAX_SPP_CONNECTIONS
#define MAX_NO_BNEP_SERVICES 1
#define MAX_NO_BNEP_CHANNELS MAX_SPP_CONNECTIONS
#define MAX_NO_DB_MEM_DEVICE_LINK_KEYS  2
#define MAX_NO_DB_MEM_DEVICE_NAMES 0
#define MAX_NO_DB_MEM_SERVICES 1
#endif

#endif
