################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/network/accept.c \
../src/network/accept4.c \
../src/network/bind.c \
../src/network/connect.c \
../src/network/dn_comp.c \
../src/network/dn_expand.c \
../src/network/dn_skipname.c \
../src/network/dns_parse.c \
../src/network/ent.c \
../src/network/ether.c \
../src/network/freeaddrinfo.c \
../src/network/gai_strerror.c \
../src/network/getaddrinfo.c \
../src/network/gethostbyaddr.c \
../src/network/gethostbyaddr_r.c \
../src/network/gethostbyname.c \
../src/network/gethostbyname2.c \
../src/network/gethostbyname2_r.c \
../src/network/gethostbyname_r.c \
../src/network/getifaddrs.c \
../src/network/getnameinfo.c \
../src/network/getpeername.c \
../src/network/getservbyname.c \
../src/network/getservbyname_r.c \
../src/network/getservbyport.c \
../src/network/getservbyport_r.c \
../src/network/getsockname.c \
../src/network/getsockopt.c \
../src/network/h_errno.c \
../src/network/herror.c \
../src/network/hstrerror.c \
../src/network/htonl.c \
../src/network/htons.c \
../src/network/if_freenameindex.c \
../src/network/if_indextoname.c \
../src/network/if_nameindex.c \
../src/network/if_nametoindex.c \
../src/network/in6addr_any.c \
../src/network/in6addr_loopback.c \
../src/network/inet_addr.c \
../src/network/inet_aton.c \
../src/network/inet_legacy.c \
../src/network/inet_ntoa.c \
../src/network/inet_ntop.c \
../src/network/inet_pton.c \
../src/network/listen.c \
../src/network/lookup_ipliteral.c \
../src/network/lookup_name.c \
../src/network/lookup_serv.c \
../src/network/netlink.c \
../src/network/netname.c \
../src/network/ns_parse.c \
../src/network/ntohl.c \
../src/network/ntohs.c \
../src/network/proto.c \
../src/network/recv.c \
../src/network/recvfrom.c \
../src/network/recvmmsg.c \
../src/network/recvmsg.c \
../src/network/res_init.c \
../src/network/res_mkquery.c \
../src/network/res_msend.c \
../src/network/res_query.c \
../src/network/res_querydomain.c \
../src/network/res_send.c \
../src/network/res_state.c \
../src/network/resolvconf.c \
../src/network/send.c \
../src/network/sendmmsg.c \
../src/network/sendmsg.c \
../src/network/sendto.c \
../src/network/serv.c \
../src/network/setsockopt.c \
../src/network/shutdown.c \
../src/network/sockatmark.c \
../src/network/socket.c \
../src/network/socketpair.c 

C_DEPS += \
./src/network/accept.d \
./src/network/accept4.d \
./src/network/bind.d \
./src/network/connect.d \
./src/network/dn_comp.d \
./src/network/dn_expand.d \
./src/network/dn_skipname.d \
./src/network/dns_parse.d \
./src/network/ent.d \
./src/network/ether.d \
./src/network/freeaddrinfo.d \
./src/network/gai_strerror.d \
./src/network/getaddrinfo.d \
./src/network/gethostbyaddr.d \
./src/network/gethostbyaddr_r.d \
./src/network/gethostbyname.d \
./src/network/gethostbyname2.d \
./src/network/gethostbyname2_r.d \
./src/network/gethostbyname_r.d \
./src/network/getifaddrs.d \
./src/network/getnameinfo.d \
./src/network/getpeername.d \
./src/network/getservbyname.d \
./src/network/getservbyname_r.d \
./src/network/getservbyport.d \
./src/network/getservbyport_r.d \
./src/network/getsockname.d \
./src/network/getsockopt.d \
./src/network/h_errno.d \
./src/network/herror.d \
./src/network/hstrerror.d \
./src/network/htonl.d \
./src/network/htons.d \
./src/network/if_freenameindex.d \
./src/network/if_indextoname.d \
./src/network/if_nameindex.d \
./src/network/if_nametoindex.d \
./src/network/in6addr_any.d \
./src/network/in6addr_loopback.d \
./src/network/inet_addr.d \
./src/network/inet_aton.d \
./src/network/inet_legacy.d \
./src/network/inet_ntoa.d \
./src/network/inet_ntop.d \
./src/network/inet_pton.d \
./src/network/listen.d \
./src/network/lookup_ipliteral.d \
./src/network/lookup_name.d \
./src/network/lookup_serv.d \
./src/network/netlink.d \
./src/network/netname.d \
./src/network/ns_parse.d \
./src/network/ntohl.d \
./src/network/ntohs.d \
./src/network/proto.d \
./src/network/recv.d \
./src/network/recvfrom.d \
./src/network/recvmmsg.d \
./src/network/recvmsg.d \
./src/network/res_init.d \
./src/network/res_mkquery.d \
./src/network/res_msend.d \
./src/network/res_query.d \
./src/network/res_querydomain.d \
./src/network/res_send.d \
./src/network/res_state.d \
./src/network/resolvconf.d \
./src/network/send.d \
./src/network/sendmmsg.d \
./src/network/sendmsg.d \
./src/network/sendto.d \
./src/network/serv.d \
./src/network/setsockopt.d \
./src/network/shutdown.d \
./src/network/sockatmark.d \
./src/network/socket.d \
./src/network/socketpair.d 

OBJS += \
./src/network/accept.o \
./src/network/accept4.o \
./src/network/bind.o \
./src/network/connect.o \
./src/network/dn_comp.o \
./src/network/dn_expand.o \
./src/network/dn_skipname.o \
./src/network/dns_parse.o \
./src/network/ent.o \
./src/network/ether.o \
./src/network/freeaddrinfo.o \
./src/network/gai_strerror.o \
./src/network/getaddrinfo.o \
./src/network/gethostbyaddr.o \
./src/network/gethostbyaddr_r.o \
./src/network/gethostbyname.o \
./src/network/gethostbyname2.o \
./src/network/gethostbyname2_r.o \
./src/network/gethostbyname_r.o \
./src/network/getifaddrs.o \
./src/network/getnameinfo.o \
./src/network/getpeername.o \
./src/network/getservbyname.o \
./src/network/getservbyname_r.o \
./src/network/getservbyport.o \
./src/network/getservbyport_r.o \
./src/network/getsockname.o \
./src/network/getsockopt.o \
./src/network/h_errno.o \
./src/network/herror.o \
./src/network/hstrerror.o \
./src/network/htonl.o \
./src/network/htons.o \
./src/network/if_freenameindex.o \
./src/network/if_indextoname.o \
./src/network/if_nameindex.o \
./src/network/if_nametoindex.o \
./src/network/in6addr_any.o \
./src/network/in6addr_loopback.o \
./src/network/inet_addr.o \
./src/network/inet_aton.o \
./src/network/inet_legacy.o \
./src/network/inet_ntoa.o \
./src/network/inet_ntop.o \
./src/network/inet_pton.o \
./src/network/listen.o \
./src/network/lookup_ipliteral.o \
./src/network/lookup_name.o \
./src/network/lookup_serv.o \
./src/network/netlink.o \
./src/network/netname.o \
./src/network/ns_parse.o \
./src/network/ntohl.o \
./src/network/ntohs.o \
./src/network/proto.o \
./src/network/recv.o \
./src/network/recvfrom.o \
./src/network/recvmmsg.o \
./src/network/recvmsg.o \
./src/network/res_init.o \
./src/network/res_mkquery.o \
./src/network/res_msend.o \
./src/network/res_query.o \
./src/network/res_querydomain.o \
./src/network/res_send.o \
./src/network/res_state.o \
./src/network/resolvconf.o \
./src/network/send.o \
./src/network/sendmmsg.o \
./src/network/sendmsg.o \
./src/network/sendto.o \
./src/network/serv.o \
./src/network/setsockopt.o \
./src/network/shutdown.o \
./src/network/sockatmark.o \
./src/network/socket.o \
./src/network/socketpair.o 


# Each subdirectory must supply rules for building sources it contributes
src/network/%.o: ../src/network/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mthumb-interwork -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g3 -Wstack-usage=100 -nostdinc -D_XOPEN_SOURCE=700 -I"C:\trunk_base\trunk\musl-1.1.18\arch\arm" -I"C:\trunk_base\trunk\musl-1.1.18\src\internal" -I"C:\trunk_base\trunk\musl-1.1.18\include" -includevis.h -std=gnu11 -ffreestanding -fexcess-precision=standard -frounding-math -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

