/* echonet_cfg.h */
#ifndef TOPPERS_ECHONET_CFG_H
#define TOPPERS_ECHONET_CFG_H

#include "echonet_app_config.h"

#define TNUM_ENODID	2

#define TNUM_EOBJID	4

#define LOCAL_NODE_EOBJ	1
#define GENERAL_LIGHTING_CLASS_EOBJ	2
#define HUMAN_DETECTION_SENSER_ENOD	3
#define HUMAN_DETECTION_SENSOR_EOBJ	4

#define TNUM_LOCAL_NODE_EOBJ_EPRPNO	13
#define TNUM_GENERAL_LIGHTING_CLASS_EOBJ_EPRPNO	11
#define TNUM_HUMAN_DETECTION_SENSER_ENOD_EPRPNO	13
#define TNUM_HUMAN_DETECTION_SENSOR_EOBJ_EPRPNO	9

#define TNUM_LOCAL_NODE_EOBJ_EOBJNO	1
#define TNUM_HUMAN_DETECTION_SENSER_ENOD_EOBJNO	1

#ifndef TNUM_ENODADR
#define TNUM_ENODADR 100
#endif

#endif /* TOPPERS_ECHONET_CFG_H */

