/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tLight_templ.c => src/tLight.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tLight_tecsgen.h"
#include "gpio_api.h"
#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eLight
 * entry port: eLight
 * signature:  sLight
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eLight_setOn
 * name:         eLight_setOn
 * global_name:  tLight_eLight_setOn
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
/* 電源LED */
gpio_t pow_led;
/* リレー出力 */
gpio_t relay_sw;
void
eLight_setOn(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
	} 
	gpio_write(&pow_led, 1);
	gpio_write(&relay_sw, 1);
	syslog(LOG_NOTICE,"LED ON");
}

/* #[<ENTRY_FUNC>]# eLight_setOff
 * name:         eLight_setOff
 * global_name:  tLight_eLight_setOff
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eLight_setOff(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	gpio_write(&pow_led, 0);
	gpio_write(&relay_sw, 0);
	syslog(LOG_NOTICE,"LED OFF");
	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
