#include "echonet.h"
#define MAIN_PRIORITY 5
#define ECHONET_MAIN_STACK_SIZE	1024
#define EOJ_X3_NODE_PROFILE 1
#define EOJ_X3_GAS_HEAT_PUMP-TYPE_COMMERCIAL_AIR_CONDITIONER_(OUTDOOR_UNIT)_CLASS 1
/*業務用ガスヒートポンプエアコン室外機*/
