################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_UPPER_SRCS := 
ASM_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
PP_SRCS := 
P_UPPER_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
C_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
ARCHIVES := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
ASM_UPPER_DEPS := 
SX_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
crt/arm \
crt \
src/aio \
src/complex \
src/conf \
src/crypt \
src/ctype \
src/dirent \
src/env \
src/errno \
src/exit \
src/exit/arm \
src/fcntl \
src/fenv \
src/fenv/arm \
src/internal \
src/ipc \
src/ldso \
src/ldso/arm \
src/legacy \
src/linux \
src/locale \
src/math \
src/math/arm \
src/misc \
src/mman \
src/mq \
src/multibyte \
src/network \
src/passwd \
src/prng \
src/process \
src/regex \
src/sched \
src/search \
src/select \
src/setjmp/arm \
src/signal/arm \
src/signal \
src/stat \
src/stdio \
src/stdlib \
src/string/arm \
src/string \
src/temp \
src/termios \
src/thread \
src/thread/arm \
src/time \
src/unistd \

